=== kalkulacka-one/kalkulacka/packages/schema/schemas/organization.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://schema.kalkulacka.one/organization.schema.json",
	"title": "Organization",
	"description": "Organization is a group of people, for example a political party, a movement, etc.",
	"type": "object",
	"$defs": {
		"person": {
			"title": "Person",
			"description": "Reference to a person",
			"type": "object",
			"properties": {
				"id": {
					"$ref": "./person.schema.json#/properties/id"
				},
				"type": {
					"type": "string",
					"const": "person"
				}
			},
			"unevaluatedProperties": false,
			"required": ["id", "type"]
		},
		"organization": {
			"title": "Organization",
			"description": "Reference to an organization",
			"type": "object",
			"properties": {
				"id": {
					"$ref": "./organization.schema.json#/properties/id"
				},
				"type": {
					"type": "string",
					"const": "organization"
				}
			},
			"unevaluatedProperties": false,
			"required": ["id", "type"]
		}
	},
	"properties": {
		"id": {
			"title": "ID",
			"description": "Unique identifier of an organization in the format of UUID",
			"type": "string",
			"format": "uuid",
			"examples": ["5fb7d561-6e93-45c2-9c75-6a1f2b11deb4"]
		},
		"name": {
			"title": "Name",
			"description": "Organization's preferred full name",
			"type": "string"
		},
		"officialName": {
			"title": "Short name",
			"description": "Organization's official name with an unlimited length",
			"type": "string"
		},
		"shortName": {
			"title": "Short name",
			"description": "Organization's short name with max. 25 characters",
			"maxLength": 25,
			"type": "string"
		},
		"abbreviation": {
			"title": "Abbreviation",
			"description": "Organization's abbreviation with max. 15 characters",
			"maxLength": 15,
			"type": "string"
		},
		"sortName": {
			"description": "A name to use in a lexicographically ordered list",
			"type": "string"
		},
		"alternateNames": {
			"description": "Alternate names to use for example in search",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"images": {
			"$ref": "./images.schema.json"
		},
		"type": {
			"title": "Organization type",
			"description": "Whether the organization is a political party/movement, coalition or a candidate list",
			"type": "string",
			"enum": ["party", "coalition", "candidate-list"]
		},
		"members": {
			"title": "Members",
			"description": "List of members of an organization",
			"type": "array",
			"minItems": 1,
			"items": {
				"oneOf": [
					{
						"$ref": "#/$defs/person"
					},
					{
						"$ref": "#/$defs/organization"
					}
				]
			}
		}
	},
	"unevaluatedProperties": false,
	"required": ["id", "name"],
	"anyOf": [
		{
			"required": ["shortName"]
		},
		{
			"required": ["abbreviation"]
		}
	]
}

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/17-praha-12/organizations.json
[
  {
    "id": "081afd8b-19c0-456a-a532-c53385383e0a",
    "name": "ANO+AUTO",
    "sortName": "ANO+AUTO",
    "shortName": "ANO+AUTO",
    "type": "candidate-list"
  },
  {
    "id": "29fcc360-87ef-4800-ac24-b1bc2b2057bd",
    "name": "KDU+ODS+STA+TOP",
    "sortName": "KDU+ODS+STA+TOP",
    "shortName": "KDU+ODS+STA+TOP",
    "type": "candidate-list"
  },
  {
    "id": "31ef10ae-3173-4397-a4fd-95c5ff2f1361",
    "name": "Piráti+LES",
    "sortName": "Piráti+LES",
    "shortName": "Piráti+LES",
    "type": "candidate-list"
  },
  {
    "id": "758b3394-1927-477c-81bb-4bb4605fd3ef",
    "name": "SOCDEM",
    "sortName": "SOCDEM",
    "shortName": "SOCDEM",
    "type": "candidate-list"
  },
  {
    "id": "5cb5d56c-688e-4b55-a801-8a803d939aab",
    "name": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "shortName": "SPD+Trikolora",
    "type": "candidate-list"
  },
  {
    "id": "7dfbba65-9e0f-4654-bf9b-81eca8783f8f",
    "name": "Švýcar. demokr.",
    "sortName": "Švýcar. demokr.",
    "shortName": "Švýcar. demokr.",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/krajske-2024/13-moravskoslezsky/organizations.json
[
  {
    "id": "37cb458c-0df8-43b0-b76c-719c41a2e06d",
    "name": "SPOLU MSK",
    "shortName": "KDU+ODS+TOP 09",
    "sortName": "KDU+ODS+TOP 09",
    "type": "candidate-list"
  },
  {
    "id": "f1794e0e-d4f6-42b1-9b97-7eb2d17759b4",
    "name": "Moravané",
    "shortName": "Moravané",
    "sortName": "Moravané",
    "type": "candidate-list"
  },
  {
    "id": "4320bb33-7951-4eea-ab40-c7b7bc295e5e",
    "name": "PŘÍSAHA občanské hnutí",
    "shortName": "PŘÍSAHA",
    "sortName": "PŘÍSAHA",
    "type": "candidate-list"
  },
  {
    "id": "ba7558ba-86af-4e2c-a340-661bab7aa0ad",
    "name": "REFERENDUM - Hlas Lidu",
    "shortName": "REFERENDUM",
    "sortName": "REFERENDUM",
    "type": "candidate-list"
  },
  {
    "id": "bddde800-c0a9-49a3-9712-581e0958842a",
    "name": "Sociální demokracie",
    "shortName": "SOCDEM",
    "sortName": "SOCDEM",
    "type": "candidate-list"
  },
  {
    "id": "c96596dd-f265-44e9-b31d-93dd39e055c4",
    "name": "SPD, Trikolora a PRO",
    "shortName": "SPD+Trikol+PRO",
    "sortName": "SPD+Trikol+PRO",
    "type": "candidate-list"
  },
  {
    "id": "e8207c2e-ca1d-4f0f-9b22-b1f45cd45521",
    "name": "STAROSTOVÉ A OSOBNOSTI PRO KRAJ",
    "shortName": "STAN+OK",
    "sortName": "STAN+OK",
    "type": "candidate-list"
  },
  {
    "id": "5cf61e1b-3b2a-4a02-bd85-4ada2d4a8080",
    "name": "Švýcarská demokracie (www.svycarska-demokracie.cz)",
    "shortName": "Švýcar. demokr.",
    "sortName": "Švýcar. demokr.",
    "type": "candidate-list"
  },
  {
    "id": "1a9e2e16-07c1-4ac0-9fda-7d94d1a011ab",
    "name": "ANO 2011",
    "shortName": "ANO",
    "sortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "cb5f5ac1-4338-4274-a52e-6311dd325d6b",
    "name": "STAČILO!, koalice Komunistické strany Čech a Moravy a České strany národně sociální",
    "shortName": "ČSNS+KSČM",
    "sortName": "ČSNS+KSČM",
    "type": "candidate-list"
  },
  {
    "id": "bd130e38-69ef-4af7-8b78-51769b4ec94c",
    "name": "ČSSD A NEZÁVISLÉ OSOBNOSTI",
    "shortName": "ČSSD+DOMOV",
    "sortName": "ČSSD+DOMOV",
    "type": "candidate-list"
  },
  {
    "id": "3ebb8278-ed49-4c8d-a029-fba792390303",
    "name": "Demokratická strana zelených - ZA PRÁVA ZVÍŘAT",
    "shortName": "DSZ-ZA PR.ZVÍŘ.",
    "sortName": "DSZ-ZA PR.ZVÍŘ.",
    "type": "candidate-list"
  },
  {
    "id": "61dfb541-cf38-4c81-aae5-dd9f62ec5fcc",
    "name": "Česká pirátská strana",
    "shortName": "Piráti",
    "sortName": "Piráti",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/41-benesov/organizations.json
[
  {
    "id": "e8833483-680f-435a-af44-b759327578c8",
    "name": "ANO",
    "sortName": "ANO",
    "shortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "6af5fa71-2a70-430e-9b29-45ead10d7018",
    "name": "ČSSD",
    "sortName": "ČSSD",
    "shortName": "ČSSD",
    "type": "candidate-list"
  },
  {
    "id": "fd9e3911-59bb-468e-ade0-eaa3601de370",
    "name": "KONS+ODS+Mon+Sv",
    "sortName": "KONS+ODS+Mon+Sv",
    "shortName": "KONS+ODS+Mon+Sv",
    "type": "candidate-list"
  },
  {
    "id": "fac96e1b-54cc-4cc0-840e-9443f154c03f",
    "name": "Piráti",
    "sortName": "Piráti",
    "shortName": "Piráti",
    "type": "candidate-list"
  },
  {
    "id": "5cb5d56c-688e-4b55-a801-8a803d939aab",
    "name": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "shortName": "SPD+Trikolora",
    "type": "candidate-list"
  },
  {
    "id": "01d12899-6c90-4cc3-bb57-a21d5a927529",
    "name": "TOP 09",
    "sortName": "TOP 09",
    "shortName": "TOP 09",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/krajske-2024/4-karlovarsky/organizations.json
[
  {
    "id": "29ebf171-b3d6-4099-af86-a266f0f259ee",
    "name": "ANO 2011",
    "shortName": "ANO",
    "sortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "3e81c7e9-c756-4148-a1ff-28dda2396624",
    "name": "Koalice SNK 1 - Starostové našeho kraje a KDU-ČSL",
    "shortName": "KDU-ČSL+SNK 1",
    "sortName": "KDU-ČSL+SNK 1",
    "type": "candidate-list"
  },
  {
    "id": "6d99b168-c76e-4e70-9daf-998266c4ec3e",
    "name": "Komunistická strana Čech a Moravy",
    "shortName": "KSČM",
    "sortName": "KSČM",
    "type": "candidate-list"
  },
  {
    "id": "101ab1d7-0e4b-42f1-9c93-dde49014a1dd",
    "name": "MÍSTNÍ HNUTÍ NEZÁVISLÝCH ZA HARMONICKÝ ROZVOJ OBCÍ A MĚST",
    "shortName": "MÍSTNÍ HNHRM",
    "sortName": "MÍSTNÍ HNHRM",
    "type": "candidate-list"
  },
  {
    "id": "71849ea2-1d40-44be-9b81-ddc09c46a149",
    "name": "Občanská demokratická strana",
    "shortName": "ODS",
    "sortName": "ODS",
    "type": "candidate-list"
  },
  {
    "id": "c3439335-e3a2-4fb9-89d8-b8dc3d8e8756",
    "name": "PŘÍSAHA občanské hnutí",
    "shortName": "PŘÍSAHA",
    "sortName": "PŘÍSAHA",
    "type": "candidate-list"
  },
  {
    "id": "ba85e418-219f-4d04-b65e-8678dcc5e310",
    "name": "Správná Volba PRO kraj",
    "shortName": "PRO2022+SpV",
    "sortName": "PRO2022+SpV",
    "type": "candidate-list"
  },
  {
    "id": "8006a2f1-0846-4def-a198-ec67e2455321",
    "name": "H L A S pro Karlovarský kraj",
    "shortName": "SD-SN+SproK",
    "sortName": "SD-SN+SproK",
    "type": "candidate-list"
  },
  {
    "id": "ad1f1155-1220-4927-934d-f07c038e7de6",
    "name": "Sociální demokracie",
    "shortName": "SOCDEM",
    "sortName": "SOCDEM",
    "type": "candidate-list"
  },
  {
    "id": "68876af1-bb46-4f68-84bb-bd0d30546e49",
    "name": "SPD a Trikolora",
    "shortName": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "type": "candidate-list"
  },
  {
    "id": "63b54792-1c06-4e7c-85a3-6021ed3a61a7",
    "name": "SRDCEM PRO ...",
    "shortName": "SRDCEM PRO ...",
    "sortName": "SRDCEM PRO ...",
    "type": "candidate-list"
  },
  {
    "id": "74b5fc1d-cb11-4498-94ef-d38ef1472e81",
    "name": "Svobodní a Soukromníci",
    "shortName": "Svobod+Soukrom",
    "sortName": "Svobod+Soukrom",
    "type": "candidate-list"
  },
  {
    "id": "c448dd2a-d68f-4117-a735-89a960784c70",
    "name": "Švýcarská demokracie (www.svycarska-demokracie.cz)",
    "shortName": "Švýcar. demokr.",
    "sortName": "Švýcar. demokr.",
    "type": "candidate-list"
  },
  {
    "id": "d26161a4-cd2b-4f35-9930-21690e7372a7",
    "name": "Vize pro Karlovarský kraj",
    "shortName": "Vize KVK",
    "sortName": "Vize KVK",
    "type": "candidate-list"
  },
  {
    "id": "8842debd-03f3-43a6-96f0-82fed6d8a2e6",
    "name": "Demokratická strana zelených - ZA PRÁVA ZVÍŘAT",
    "shortName": "DSZ-ZA PR.ZVÍŘ.",
    "sortName": "DSZ-ZA PR.ZVÍŘ.",
    "type": "candidate-list"
  },
  {
    "id": "46ecc231-c22e-4c8e-b21c-fcc2e8916ef5",
    "name": "Česká pirátská strana",
    "shortName": "Piráti",
    "sortName": "Piráti",
    "type": "candidate-list"
  },
  {
    "id": "1cf7c04f-408e-4813-83ab-774da12e7c6b",
    "name": "STAROSTOVÉ A NEZÁVISLÍ",
    "shortName": "STAN",
    "sortName": "STAN",
    "type": "candidate-list"
  },
  {
    "id": "2d4d9724-d4d8-4527-b180-3245f503e0b2",
    "name": "Volba pro kraj",
    "shortName": "VOK",
    "sortName": "VOK",
    "type": "candidate-list"
  },
  {
    "id": "dc4750ce-1403-4930-9c29-d7f01ece2275",
    "name": "Volt Česko",
    "shortName": "Volt",
    "sortName": "Volt",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/74-karvina/organizations.json
[
  {
    "id": "6af5fa71-2a70-430e-9b29-45ead10d7018",
    "name": "ČSSD",
    "sortName": "ČSSD",
    "shortName": "ČSSD",
    "type": "candidate-list"
  },
  {
    "id": "64a0008f-2d59-4a0f-961f-8fa2fd1a7835",
    "name": "KDU+ODS+TOP 09",
    "sortName": "KDU+ODS+TOP 09",
    "shortName": "KDU+ODS+TOP 09",
    "type": "candidate-list"
  },
  {
    "id": "758b3394-1927-477c-81bb-4bb4605fd3ef",
    "name": "SOCDEM",
    "sortName": "SOCDEM",
    "shortName": "SOCDEM",
    "type": "candidate-list"
  },
  {
    "id": "5cb5d56c-688e-4b55-a801-8a803d939aab",
    "name": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "shortName": "SPD+Trikolora",
    "type": "candidate-list"
  },
  {
    "id": "7dfbba65-9e0f-4654-bf9b-81eca8783f8f",
    "name": "Švýcar. demokr.",
    "sortName": "Švýcar. demokr.",
    "shortName": "Švýcar. demokr.",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/krajske-2024/1-stredocesky/organizations.json
[
  {
    "id": "7a481608-e155-4d61-a4b3-5e01cd0f5769",
    "name": "ANO 2011",
    "shortName": "ANO",
    "sortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "cd129b70-b820-4627-9c7c-681569714f6a",
    "name": "JISTOTA A BUDOUCNOST",
    "shortName": "JAB",
    "sortName": "JAB",
    "type": "candidate-list"
  },
  {
    "id": "6a5ac75d-7366-4709-b929-e3eaf696c900",
    "name": "SPOLU (ODS + TOP 09 + KDU-ČSL)",
    "shortName": "KDU+ODS+TOP 09",
    "sortName": "KDU+ODS+TOP 09",
    "type": "candidate-list"
  },
  {
    "id": "f7a556a9-6bc6-424c-b989-8c4751e17b09",
    "name": "Liberální aliance nezávislých občanů",
    "shortName": "LANO",
    "sortName": "LANO",
    "type": "candidate-list"
  },
  {
    "id": "b0983832-dcbd-4cfa-a91c-793a89b5c0bc",
    "name": "LEPŠÍ ŽIVOT PRO LIDI - min. mzda 70.000 Kč, min. důchod 50.000 Kč, návrat cen energií na ceny z roku 2019, v obchodech zboží nejvyšší kvality za ceny dostupné pro každého, zrušení daně z nemovitostí, STOP válce",
    "shortName": "LŽPL",
    "sortName": "LŽPL",
    "type": "candidate-list"
  },
  {
    "id": "93799b7b-d2a8-4ef6-b6c3-4e22cf65e711",
    "name": "ANO LEPŠÍ ČESKO S MIMOZEMŠŤANY A OBČANY MOTORISTY - (dostupnější bydlení, jízdné zdarma školákům a studentům, …)",
    "shortName": "mimozemstani.eu",
    "sortName": "mimozemstani.eu",
    "type": "candidate-list"
  },
  {
    "id": "c8b86b92-e025-4316-84f9-85cd9c98f779",
    "name": "ČISTÝ A BEZPEČNÝ KRAJ",
    "shortName": "NDDSSSBEZULANS",
    "sortName": "NDDSSSBEZULANS",
    "type": "candidate-list"
  },
  {
    "id": "f2c4494f-64dd-4c6e-8eec-f566d38648a8",
    "name": "PŘÍSAHA občanské hnutí",
    "shortName": "PŘÍSAHA",
    "sortName": "PŘÍSAHA",
    "type": "candidate-list"
  },
  {
    "id": "faab6ecc-63c9-4d83-aa18-9d5c3beacbbc",
    "name": "Sdružení pro Místní Správu",
    "shortName": "SMS",
    "sortName": "SMS",
    "type": "candidate-list"
  },
  {
    "id": "34b42bea-9f07-497d-b102-2ea5a77ff884",
    "name": "Sociální demokracie",
    "shortName": "SOCDEM",
    "sortName": "SOCDEM",
    "type": "candidate-list"
  },
  {
    "id": "1b3c52cc-c77b-4ccb-9c5e-fa5f43511e93",
    "name": "STAROSTOVÉ A NEZÁVISLÍ",
    "shortName": "STAN",
    "sortName": "STAN",
    "type": "candidate-list"
  },
  {
    "id": "89e41669-1b3e-47ca-a6f7-e3bfc0d71021",
    "name": "Švýcarská demokracie (www.svycarska-demokracie.cz)",
    "shortName": "Švýcar. demokr.",
    "sortName": "Švýcar. demokr.",
    "type": "candidate-list"
  },
  {
    "id": "b00f7c0e-e296-44f8-9638-47ba6ec17455",
    "name": "Zelení a SEN 21",
    "shortName": "Zelení+SEN 21",
    "sortName": "Zelení+SEN 21",
    "type": "candidate-list"
  },
  {
    "id": "cc79df2e-8411-42ad-a9bf-be2feda597e4",
    "name": "STAČILO! - SPOJENÁ LEVICE KSČM, ČSSD A ČSNS",
    "shortName": "ČSNS+KSČM+ČSSD",
    "sortName": "ČSNS+KSČM+ČSSD",
    "type": "candidate-list"
  },
  {
    "id": "bd9c43e4-2d70-464f-8501-071942911220",
    "name": "Demokratická strana zelených - ZA PRÁVA ZVÍŘAT",
    "shortName": "DSZ-ZA PR.ZVÍŘ.",
    "sortName": "DSZ-ZA PR.ZVÍŘ.",
    "type": "candidate-list"
  },
  {
    "id": "58cc3aa5-9649-4485-8977-636f8d48b06c",
    "name": "Česká pirátská strana",
    "shortName": "Piráti",
    "sortName": "Piráti",
    "type": "candidate-list"
  },
  {
    "id": "cfce1eae-5d9e-48a8-832f-9d8508d8ed1e",
    "name": "SPD, Trikolora a PRO",
    "shortName": "SPD+Trikol+PRO",
    "sortName": "SPD+Trikol+PRO",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/77-vsetin/organizations.json
[
  {
    "id": "e8833483-680f-435a-af44-b759327578c8",
    "name": "ANO",
    "sortName": "ANO",
    "shortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "46927f39-fffa-44de-aa6b-ee76f53052bf",
    "name": "KDU-ČSL",
    "sortName": "KDU-ČSL",
    "shortName": "KDU-ČSL",
    "type": "candidate-list"
  },
  {
    "id": "5cb5d56c-688e-4b55-a801-8a803d939aab",
    "name": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "shortName": "SPD+Trikolora",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/35-jablonec-nad-nisou/organizations.json
[
  {
    "id": "e8833483-680f-435a-af44-b759327578c8",
    "name": "ANO",
    "sortName": "ANO",
    "shortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "a32089e0-5fda-44fb-b12a-c97139bdb785",
    "name": "APB",
    "sortName": "APB",
    "shortName": "APB",
    "type": "candidate-list"
  },
  {
    "id": "64a0008f-2d59-4a0f-961f-8fa2fd1a7835",
    "name": "KDU+ODS+TOP 09",
    "sortName": "KDU+ODS+TOP 09",
    "shortName": "KDU+ODS+TOP 09",
    "type": "candidate-list"
  },
  {
    "id": "50e58d59-db2e-4949-a1c8-58cf68bd21f5",
    "name": "SEN 21",
    "sortName": "SEN 21",
    "shortName": "SEN 21",
    "type": "candidate-list"
  },
  {
    "id": "ff170d83-5e25-485e-979d-a5d58081d490",
    "name": "SLK",
    "sortName": "SLK",
    "shortName": "SLK",
    "type": "candidate-list"
  },
  {
    "id": "5cb5d56c-688e-4b55-a801-8a803d939aab",
    "name": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "shortName": "SPD+Trikolora",
    "type": "candidate-list"
  }
]
