=== kalkulacka-one/kalkulacka/packages/schema/schemas/organization.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://schema.kalkulacka.one/organization.schema.json",
	"title": "Organization",
	"description": "Organization is a group of people, for example a political party, a movement, etc.",
	"type": "object",
	"$defs": {
		"person": {
			"title": "Person",
			"description": "Reference to a person",
			"type": "object",
			"properties": {
				"id": {
					"$ref": "./person.schema.json#/properties/id"
				},
				"type": {
					"type": "string",
					"const": "person"
				}
			},
			"unevaluatedProperties": false,
			"required": ["id", "type"]
		},
		"organization": {
			"title": "Organization",
			"description": "Reference to an organization",
			"type": "object",
			"properties": {
				"id": {
					"$ref": "./organization.schema.json#/properties/id"
				},
				"type": {
					"type": "string",
					"const": "organization"
				}
			},
			"unevaluatedProperties": false,
			"required": ["id", "type"]
		}
	},
	"properties": {
		"id": {
			"title": "ID",
			"description": "Unique identifier of an organization in the format of UUID",
			"type": "string",
			"format": "uuid",
			"examples": ["5fb7d561-6e93-45c2-9c75-6a1f2b11deb4"]
		},
		"name": {
			"title": "Name",
			"description": "Organization's preferred full name",
			"type": "string"
		},
		"officialName": {
			"title": "Short name",
			"description": "Organization's official name with an unlimited length",
			"type": "string"
		},
		"shortName": {
			"title": "Short name",
			"description": "Organization's short name with max. 25 characters",
			"maxLength": 25,
			"type": "string"
		},
		"abbreviation": {
			"title": "Abbreviation",
			"description": "Organization's abbreviation with max. 15 characters",
			"maxLength": 15,
			"type": "string"
		},
		"sortName": {
			"description": "A name to use in a lexicographically ordered list",
			"type": "string"
		},
		"alternateNames": {
			"description": "Alternate names to use for example in search",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"images": {
			"$ref": "./images.schema.json"
		},
		"type": {
			"title": "Organization type",
			"description": "Whether the organization is a political party/movement, coalition or a candidate list",
			"type": "string",
			"enum": ["party", "coalition", "candidate-list"]
		},
		"members": {
			"title": "Members",
			"description": "List of members of an organization",
			"type": "array",
			"minItems": 1,
			"items": {
				"oneOf": [
					{
						"$ref": "#/$defs/person"
					},
					{
						"$ref": "#/$defs/organization"
					}
				]
			}
		}
	},
	"unevaluatedProperties": false,
	"required": ["id", "name"],
	"anyOf": [
		{
			"required": ["shortName"]
		},
		{
			"required": ["abbreviation"]
		}
	]
}

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/59-brno-mesto/organizations.json
[
  {
    "id": "46927f39-fffa-44de-aa6b-ee76f53052bf",
    "name": "KDU-ČSL",
    "sortName": "KDU-ČSL",
    "shortName": "KDU-ČSL",
    "type": "candidate-list"
  },
  {
    "id": "de9476eb-0063-47c0-9ada-d8c3fd0609f3",
    "name": "SOCDEM+ANO",
    "sortName": "SOCDEM+ANO",
    "shortName": "SOCDEM+ANO",
    "type": "candidate-list"
  },
  {
    "id": "ff1877fc-95a7-430a-bb90-2088a9983f9d",
    "name": "SOM",
    "sortName": "SOM",
    "shortName": "SOM",
    "type": "candidate-list"
  },
  {
    "id": "5cb5d56c-688e-4b55-a801-8a803d939aab",
    "name": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "shortName": "SPD+Trikolora",
    "type": "candidate-list"
  },
  {
    "id": "15630910-e388-4038-bfeb-04781a6cf2d6",
    "name": "STAN",
    "sortName": "STAN",
    "shortName": "STAN",
    "type": "candidate-list"
  },
  {
    "id": "6797d805-5e00-4f26-acb5-a61f8b4895ba",
    "name": "Svobodní",
    "sortName": "Svobodní",
    "shortName": "Svobodní",
    "type": "candidate-list"
  },
  {
    "id": "b79dfa80-b1a3-4c13-bf44-4421f32d6c17",
    "name": "Zel+ODS+Pir+TOP",
    "sortName": "Zel+ODS+Pir+TOP",
    "shortName": "Zel+ODS+Pir+TOP",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/65-sumperk/organizations.json
[
  {
    "id": "e8833483-680f-435a-af44-b759327578c8",
    "name": "ANO",
    "sortName": "ANO",
    "shortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "8331b263-fda5-459d-b28c-ddb84f281963",
    "name": "NK",
    "sortName": "NK",
    "shortName": "NK",
    "type": "candidate-list"
  },
  {
    "id": "6797d805-5e00-4f26-acb5-a61f8b4895ba",
    "name": "Svobodní",
    "sortName": "Svobodní",
    "shortName": "Svobodní",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/29-litomerice/organizations.json
[
  {
    "id": "e8833483-680f-435a-af44-b759327578c8",
    "name": "ANO",
    "sortName": "ANO",
    "shortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "bc382abd-a642-43b9-b64e-0ca563ac4ca3",
    "name": "ČSNS+KSČM+SD-SN",
    "sortName": "ČSNS+KSČM+SD-SN",
    "shortName": "ČSNS+KSČM+SD-SN",
    "type": "candidate-list"
  },
  {
    "id": "6af5fa71-2a70-430e-9b29-45ead10d7018",
    "name": "ČSSD",
    "sortName": "ČSSD",
    "shortName": "ČSSD",
    "type": "candidate-list"
  },
  {
    "id": "64a0008f-2d59-4a0f-961f-8fa2fd1a7835",
    "name": "KDU+ODS+TOP 09",
    "sortName": "KDU+ODS+TOP 09",
    "shortName": "KDU+ODS+TOP 09",
    "type": "candidate-list"
  },
  {
    "id": "fac96e1b-54cc-4cc0-840e-9443f154c03f",
    "name": "Piráti",
    "sortName": "Piráti",
    "shortName": "Piráti",
    "type": "candidate-list"
  },
  {
    "id": "5cb5d56c-688e-4b55-a801-8a803d939aab",
    "name": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "shortName": "SPD+Trikolora",
    "type": "candidate-list"
  },
  {
    "id": "15630910-e388-4038-bfeb-04781a6cf2d6",
    "name": "STAN",
    "sortName": "STAN",
    "shortName": "STAN",
    "type": "candidate-list"
  },
  {
    "id": "6797d805-5e00-4f26-acb5-a61f8b4895ba",
    "name": "Svobodní",
    "sortName": "Svobodní",
    "shortName": "Svobodní",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/80-zlin/organizations.json
[
  {
    "id": "e8833483-680f-435a-af44-b759327578c8",
    "name": "ANO",
    "sortName": "ANO",
    "shortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "46927f39-fffa-44de-aa6b-ee76f53052bf",
    "name": "KDU-ČSL",
    "sortName": "KDU-ČSL",
    "shortName": "KDU-ČSL",
    "type": "candidate-list"
  },
  {
    "id": "6f007ce1-2275-4abc-b38f-65913d78f7e6",
    "name": "NEZ",
    "sortName": "NEZ",
    "shortName": "NEZ",
    "type": "candidate-list"
  },
  {
    "id": "8331b263-fda5-459d-b28c-ddb84f281963",
    "name": "NK",
    "sortName": "NK",
    "shortName": "NK",
    "type": "candidate-list"
  },
  {
    "id": "37a912ea-5bb0-476f-a124-6729ba67cc7e",
    "name": "PRO 2022",
    "sortName": "PRO 2022",
    "shortName": "PRO 2022",
    "type": "candidate-list"
  },
  {
    "id": "15630910-e388-4038-bfeb-04781a6cf2d6",
    "name": "STAN",
    "sortName": "STAN",
    "shortName": "STAN",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/71-ostrava-mesto/organizations.json
[
  {
    "id": "e8833483-680f-435a-af44-b759327578c8",
    "name": "ANO",
    "sortName": "ANO",
    "shortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "bc382abd-a642-43b9-b64e-0ca563ac4ca3",
    "name": "ČSNS+KSČM+SD-SN",
    "sortName": "ČSNS+KSČM+SD-SN",
    "shortName": "ČSNS+KSČM+SD-SN",
    "type": "candidate-list"
  },
  {
    "id": "20a54dd5-96f0-4740-b7e2-67f621d32715",
    "name": "Ostravak",
    "sortName": "Ostravak",
    "shortName": "Ostravak",
    "type": "candidate-list"
  },
  {
    "id": "e2e60e7a-5165-40e8-a233-068db4e79888",
    "name": "ReMeK",
    "sortName": "ReMeK",
    "shortName": "ReMeK",
    "type": "candidate-list"
  },
  {
    "id": "5cb5d56c-688e-4b55-a801-8a803d939aab",
    "name": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "shortName": "SPD+Trikolora",
    "type": "candidate-list"
  },
  {
    "id": "6797d805-5e00-4f26-acb5-a61f8b4895ba",
    "name": "Svobodní",
    "sortName": "Svobodní",
    "shortName": "Svobodní",
    "type": "candidate-list"
  },
  {
    "id": "7dfbba65-9e0f-4654-bf9b-81eca8783f8f",
    "name": "Švýcar. demokr.",
    "sortName": "Švýcar. demokr.",
    "shortName": "Švýcar. demokr.",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/11-domazlice/organizations.json
[
  {
    "id": "e8833483-680f-435a-af44-b759327578c8",
    "name": "ANO",
    "sortName": "ANO",
    "shortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "7cbe01ba-db6b-4969-a91c-68ff4e6c3f2f",
    "name": "KDU+PROPLZ+ADS",
    "sortName": "KDU+PROPLZ+ADS",
    "shortName": "KDU+PROPLZ+ADS",
    "type": "candidate-list"
  },
  {
    "id": "40a4e263-ec72-417a-8e6f-f97297351b13",
    "name": "KSČM",
    "sortName": "KSČM",
    "shortName": "KSČM",
    "type": "candidate-list"
  },
  {
    "id": "8331b263-fda5-459d-b28c-ddb84f281963",
    "name": "NK",
    "sortName": "NK",
    "shortName": "NK",
    "type": "candidate-list"
  },
  {
    "id": "f87f4d6b-f2d5-49fa-8a38-2757be7d3309",
    "name": "ODS",
    "sortName": "ODS",
    "shortName": "ODS",
    "type": "candidate-list"
  },
  {
    "id": "fac96e1b-54cc-4cc0-840e-9443f154c03f",
    "name": "Piráti",
    "sortName": "Piráti",
    "shortName": "Piráti",
    "type": "candidate-list"
  },
  {
    "id": "758b3394-1927-477c-81bb-4bb4605fd3ef",
    "name": "SOCDEM",
    "sortName": "SOCDEM",
    "shortName": "SOCDEM",
    "type": "candidate-list"
  },
  {
    "id": "5cb5d56c-688e-4b55-a801-8a803d939aab",
    "name": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "shortName": "SPD+Trikolora",
    "type": "candidate-list"
  },
  {
    "id": "15630910-e388-4038-bfeb-04781a6cf2d6",
    "name": "STAN",
    "sortName": "STAN",
    "shortName": "STAN",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/38-mlada-boleslav/organizations.json
[
  {
    "id": "e8833483-680f-435a-af44-b759327578c8",
    "name": "ANO",
    "sortName": "ANO",
    "shortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "89395259-1fd2-4a28-8a86-537ecf69944f",
    "name": "JaSaN",
    "sortName": "JaSaN",
    "shortName": "JaSaN",
    "type": "candidate-list"
  },
  {
    "id": "64a0008f-2d59-4a0f-961f-8fa2fd1a7835",
    "name": "KDU+ODS+TOP 09",
    "sortName": "KDU+ODS+TOP 09",
    "shortName": "KDU+ODS+TOP 09",
    "type": "candidate-list"
  },
  {
    "id": "758b3394-1927-477c-81bb-4bb4605fd3ef",
    "name": "SOCDEM",
    "sortName": "SOCDEM",
    "shortName": "SOCDEM",
    "type": "candidate-list"
  },
  {
    "id": "5cb5d56c-688e-4b55-a801-8a803d939aab",
    "name": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "shortName": "SPD+Trikolora",
    "type": "candidate-list"
  },
  {
    "id": "15630910-e388-4038-bfeb-04781a6cf2d6",
    "name": "STAN",
    "sortName": "STAN",
    "shortName": "STAN",
    "type": "candidate-list"
  },
  {
    "id": "0150f4df-0865-4577-8ccb-04f5b399e2a2",
    "name": "Zelení",
    "sortName": "Zelení",
    "shortName": "Zelení",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/20-praha-4/organizations.json
[
  {
    "id": "e8833483-680f-435a-af44-b759327578c8",
    "name": "ANO",
    "sortName": "ANO",
    "shortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "a32089e0-5fda-44fb-b12a-c97139bdb785",
    "name": "ANS",
    "sortName": "ANS",
    "shortName": "ANS",
    "type": "candidate-list"
  },
  {
    "id": "a32089e0-5fda-44fb-b12a-c97139bdb785",
    "name": "APB",
    "sortName": "APB",
    "shortName": "APB",
    "type": "candidate-list"
  },
  {
    "id": "89395259-1fd2-4a28-8a86-537ecf69944f",
    "name": "JaSaN",
    "sortName": "JaSaN",
    "shortName": "JaSaN",
    "type": "candidate-list"
  },
  {
    "id": "970162b0-ec51-4f39-81e7-1d99f7bd7cc3",
    "name": "KDUODSSTANPiTOP",
    "sortName": "KDUODSSTANPiTOP",
    "shortName": "KDUODSSTANPiTOP",
    "type": "candidate-list"
  },
  {
    "id": "758b3394-1927-477c-81bb-4bb4605fd3ef",
    "name": "SOCDEM",
    "sortName": "SOCDEM",
    "shortName": "SOCDEM",
    "type": "candidate-list"
  },
  {
    "id": "6797d805-5e00-4f26-acb5-a61f8b4895ba",
    "name": "Svobodní",
    "sortName": "Svobodní",
    "shortName": "Svobodní",
    "type": "candidate-list"
  },
  {
    "id": "0150f4df-0865-4577-8ccb-04f5b399e2a2",
    "name": "Zelení",
    "sortName": "Zelení",
    "shortName": "Zelení",
    "type": "candidate-list"
  }
]
