=== kalkulacka-one/kalkulacka/packages/schema/schemas/organization.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://schema.kalkulacka.one/organization.schema.json",
	"title": "Organization",
	"description": "Organization is a group of people, for example a political party, a movement, etc.",
	"type": "object",
	"$defs": {
		"person": {
			"title": "Person",
			"description": "Reference to a person",
			"type": "object",
			"properties": {
				"id": {
					"$ref": "./person.schema.json#/properties/id"
				},
				"type": {
					"type": "string",
					"const": "person"
				}
			},
			"unevaluatedProperties": false,
			"required": ["id", "type"]
		},
		"organization": {
			"title": "Organization",
			"description": "Reference to an organization",
			"type": "object",
			"properties": {
				"id": {
					"$ref": "./organization.schema.json#/properties/id"
				},
				"type": {
					"type": "string",
					"const": "organization"
				}
			},
			"unevaluatedProperties": false,
			"required": ["id", "type"]
		}
	},
	"properties": {
		"id": {
			"title": "ID",
			"description": "Unique identifier of an organization in the format of UUID",
			"type": "string",
			"format": "uuid",
			"examples": ["5fb7d561-6e93-45c2-9c75-6a1f2b11deb4"]
		},
		"name": {
			"title": "Name",
			"description": "Organization's preferred full name",
			"type": "string"
		},
		"officialName": {
			"title": "Short name",
			"description": "Organization's official name with an unlimited length",
			"type": "string"
		},
		"shortName": {
			"title": "Short name",
			"description": "Organization's short name with max. 25 characters",
			"maxLength": 25,
			"type": "string"
		},
		"abbreviation": {
			"title": "Abbreviation",
			"description": "Organization's abbreviation with max. 15 characters",
			"maxLength": 15,
			"type": "string"
		},
		"sortName": {
			"description": "A name to use in a lexicographically ordered list",
			"type": "string"
		},
		"alternateNames": {
			"description": "Alternate names to use for example in search",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"images": {
			"$ref": "./images.schema.json"
		},
		"type": {
			"title": "Organization type",
			"description": "Whether the organization is a political party/movement, coalition or a candidate list",
			"type": "string",
			"enum": ["party", "coalition", "candidate-list"]
		},
		"members": {
			"title": "Members",
			"description": "List of members of an organization",
			"type": "array",
			"minItems": 1,
			"items": {
				"oneOf": [
					{
						"$ref": "#/$defs/person"
					},
					{
						"$ref": "#/$defs/organization"
					}
				]
			}
		}
	},
	"unevaluatedProperties": false,
	"required": ["id", "name"],
	"anyOf": [
		{
			"required": ["shortName"]
		},
		{
			"required": ["abbreviation"]
		}
	]
}

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/krajske-2024/8-pardubicky/organizations.json
[
  {
    "id": "51826da1-4392-40d6-aeec-fa41c76338c8",
    "name": "ANO 2011",
    "shortName": "ANO",
    "sortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "4d90b74e-0a66-4831-8492-9cccb68206eb",
    "name": "Koalice pro Pardubický kraj",
    "shortName": "Koalice pro PaK",
    "sortName": "Koalice pro PaK",
    "type": "candidate-list"
  },
  {
    "id": "a1990571-bfe5-4edd-882b-c78832412ad2",
    "name": "ODS a TOP 09",
    "shortName": "ODS+TOP 09",
    "sortName": "ODS+TOP 09",
    "type": "candidate-list"
  },
  {
    "id": "fdaa549d-1258-4129-a219-092783b8cb61",
    "name": "Česká pirátská strana",
    "shortName": "Piráti",
    "sortName": "Piráti",
    "type": "candidate-list"
  },
  {
    "id": "38f03477-76b5-4b4f-af13-cc1a0559b83f",
    "name": "3PK - Pro prosperující Pardubický kraj",
    "shortName": "SOCDEM+VČ+SproK",
    "sortName": "SOCDEM+VČ+SproK",
    "type": "candidate-list"
  },
  {
    "id": "31b6879e-c4b9-4d93-bac2-a63698483a3f",
    "name": "NAŠE PARDUBICE - \"Nechme kraj rozkvést\"",
    "shortName": "SPDV+mimozemst.",
    "sortName": "SPDV+mimozemst.",
    "type": "candidate-list"
  },
  {
    "id": "3648451a-a937-40c7-853d-056ab4db0d0f",
    "name": "STAROSTOVÉ A NEZÁVISLÍ",
    "shortName": "STAN",
    "sortName": "STAN",
    "type": "candidate-list"
  },
  {
    "id": "9728007d-99bd-42f0-ad12-42fac41ea720",
    "name": "Švýcarská demokracie (www.svycarska-demokracie.cz)",
    "shortName": "Švýcar. demokr.",
    "sortName": "Švýcar. demokr.",
    "type": "candidate-list"
  },
  {
    "id": "eca7cc39-fd8a-43a7-a9e2-b4e41accecc6",
    "name": "STAČILO! (KSČM, ČSNS, ČSSD)",
    "shortName": "ČSNS+KSČM+ČSSD",
    "sortName": "ČSNS+KSČM+ČSSD",
    "type": "candidate-list"
  },
  {
    "id": "544129f5-4b21-4129-bc56-151ca9cc58af",
    "name": "Demokratická strana zelených - ZA PRÁVA ZVÍŘAT",
    "shortName": "DSZ-ZA PR.ZVÍŘ.",
    "sortName": "DSZ-ZA PR.ZVÍŘ.",
    "type": "candidate-list"
  },
  {
    "id": "c414fd65-e7b0-47e8-a588-739d616ba7ba",
    "name": "REFERENDUM - Hlas Lidu",
    "shortName": "REFERENDUM",
    "sortName": "REFERENDUM",
    "type": "candidate-list"
  },
  {
    "id": "3b929f67-c7b4-40bd-8974-b80cf509a4a4",
    "name": "SPD, Trikolora a PRO",
    "shortName": "SPD+Trikol+PRO",
    "sortName": "SPD+Trikol+PRO",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/krajske-2024/3-plzensky/organizations.json
[
  {
    "id": "79ee04ba-7580-425a-a98e-c0b075e33d5a",
    "name": "ANO 2011",
    "shortName": "ANO",
    "sortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "5ffd78d8-b288-4cb0-bd03-dee88a845421",
    "name": "PRO NÁŠ KRAJ – PRO PLZEŇ a KDU-ČSL s podporou Svobodných, agrárníků, starostů a sportovců",
    "shortName": "KDUČSL+PROPLZEŇ",
    "sortName": "KDUČSL+PROPLZEŇ",
    "type": "candidate-list"
  },
  {
    "id": "99957f33-eb91-45b2-bec3-55d21d91fd88",
    "name": "LEPŠÍ ŽIVOT PRO LIDI-min.mzda 70.000 Kč,min.důchod 50.000 Kč,ceny energií 2019,v obchodech zboží nej. kvality,STOP válce",
    "shortName": "LŽPL",
    "sortName": "LŽPL",
    "type": "candidate-list"
  },
  {
    "id": "2e519cd6-343e-48d6-bf57-ec589e3c1370",
    "name": "PŘÍSAHA občanské hnutí",
    "shortName": "PŘÍSAHA",
    "sortName": "PŘÍSAHA",
    "type": "candidate-list"
  },
  {
    "id": "5155ebc4-be3f-4f2a-8233-794a21239422",
    "name": "SPD a Trikolora",
    "shortName": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "type": "candidate-list"
  },
  {
    "id": "f1226ebb-3e3c-4de5-bda7-6207afa13ba6",
    "name": "STAČILO! Koalice Komunistické strany Čech a Moravy, Spojených demokratů - Sdružení nez. a České strany národně sociální",
    "shortName": "ČSNS+KSČM+SD-SN",
    "sortName": "ČSNS+KSČM+SD-SN",
    "type": "candidate-list"
  },
  {
    "id": "343b8eb2-0b15-4cc9-bc54-3aca3af432ad",
    "name": "Demokratická strana zelených - ZA PRÁVA ZVÍŘAT",
    "shortName": "DSZ-ZA PR.ZVÍŘ.",
    "sortName": "DSZ-ZA PR.ZVÍŘ.",
    "type": "candidate-list"
  },
  {
    "id": "fe221b02-2fbc-4f9d-bc5b-a76271cdd14d",
    "name": "Koruna Česká (monarchistická strana Čech, Moravy a Slezska)",
    "shortName": "Monarchiste.cz",
    "sortName": "Monarchiste.cz",
    "type": "candidate-list"
  },
  {
    "id": "19daca66-b868-4595-a135-f9b830076883",
    "name": "ČISTÝ A BEZPEČNÝ KRAJ",
    "shortName": "NDDSSSBEZULANS",
    "sortName": "NDDSSSBEZULANS",
    "type": "candidate-list"
  },
  {
    "id": "1921b97d-0f68-4430-bf14-a81951c79530",
    "name": "ODS a TOP 09 - SPOLEČNĚ DO KRAJE",
    "shortName": "ODS+TOP 09",
    "sortName": "ODS+TOP 09",
    "type": "candidate-list"
  },
  {
    "id": "1395731c-3a69-4c4a-b7b1-d4922977e5c6",
    "name": "Česká pirátská strana",
    "shortName": "Piráti",
    "sortName": "Piráti",
    "type": "candidate-list"
  },
  {
    "id": "825d5e88-d728-404b-a249-5ed1ca99d7ec",
    "name": "Sociální demokracie",
    "shortName": "SOCDEM",
    "sortName": "SOCDEM",
    "type": "candidate-list"
  },
  {
    "id": "11194177-4e6b-4835-b8c5-6559d6fbc17e",
    "name": "STAROSTOVÉ A NEZÁVISLÍ",
    "shortName": "STAN",
    "sortName": "STAN",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/50-svitavy/organizations.json
[
  {
    "id": "89395259-1fd2-4a28-8a86-537ecf69944f",
    "name": "JaSaN",
    "sortName": "JaSaN",
    "shortName": "JaSaN",
    "type": "candidate-list"
  },
  {
    "id": "aa886e40-4ca9-4d65-b909-4a15928e1861",
    "name": "KDU-ČSL+Nestran",
    "sortName": "KDU-ČSL+Nestran",
    "shortName": "KDU-ČSL+Nestran",
    "type": "candidate-list"
  },
  {
    "id": "8331b263-fda5-459d-b28c-ddb84f281963",
    "name": "NK",
    "sortName": "NK",
    "shortName": "NK",
    "type": "candidate-list"
  },
  {
    "id": "f87f4d6b-f2d5-49fa-8a38-2757be7d3309",
    "name": "ODS",
    "sortName": "ODS",
    "shortName": "ODS",
    "type": "candidate-list"
  },
  {
    "id": "5c2df6a6-1511-4f98-94eb-95dacef147d6",
    "name": "SOCDEM+SproK",
    "sortName": "SOCDEM+SproK",
    "shortName": "SOCDEM+SproK",
    "type": "candidate-list"
  },
  {
    "id": "4f390d39-afd6-4aae-a854-842dd8148163",
    "name": "SpV",
    "sortName": "SpV",
    "shortName": "SpV",
    "type": "candidate-list"
  },
  {
    "id": "1dbf4591-b049-4b3e-97c0-73f31db974d1",
    "name": "Trikolora",
    "sortName": "Trikolora",
    "shortName": "Trikolora",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/8-rokycany/organizations.json
[
  {
    "id": "e8833483-680f-435a-af44-b759327578c8",
    "name": "ANO",
    "sortName": "ANO",
    "shortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "7cbe01ba-db6b-4969-a91c-68ff4e6c3f2f",
    "name": "KDU+PROPLZ+ADS",
    "sortName": "KDU+PROPLZ+ADS",
    "shortName": "KDU+PROPLZ+ADS",
    "type": "candidate-list"
  },
  {
    "id": "46ef04cd-61f7-49cc-8f7a-169995873fe4",
    "name": "ODSMonarTOPOPAT",
    "sortName": "ODSMonarTOPOPAT",
    "shortName": "ODSMonarTOPOPAT",
    "type": "candidate-list"
  },
  {
    "id": "5cb5d56c-688e-4b55-a801-8a803d939aab",
    "name": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "shortName": "SPD+Trikolora",
    "type": "candidate-list"
  },
  {
    "id": "15630910-e388-4038-bfeb-04781a6cf2d6",
    "name": "STAN",
    "sortName": "STAN",
    "shortName": "STAN",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/krajske-2024/5-ustecky/organizations.json
[
  {
    "id": "652c1bc5-5068-409e-a32f-abde11a2dea8",
    "name": "ANO 2011",
    "shortName": "ANO",
    "sortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "512ae7b4-9151-4ec4-a392-8c83af4bb664",
    "name": "ČSSD – ČISTÝ KRAJ",
    "shortName": "ČSSD+ČiKR",
    "sortName": "ČSSD+ČiKR",
    "type": "candidate-list"
  },
  {
    "id": "90018e40-b8c7-466a-8089-da49ebac52f8",
    "name": "LEPŠÍ SEVER",
    "shortName": "LS",
    "sortName": "LS",
    "type": "candidate-list"
  },
  {
    "id": "db76be10-f51f-4d18-8e17-c41b47401291",
    "name": "LEPŠÍ ŽIVOT PRO LIDI - minimální MZDA 70.000 Kč, minimální DŮCHOD 50.000 Kč, ZRUŠENÍ daně z nemovitostí, …",
    "shortName": "ND+LŽPL",
    "sortName": "ND+LŽPL",
    "type": "candidate-list"
  },
  {
    "id": "7cee3b59-1f65-4d37-bfa6-b58cd1ac8e0c",
    "name": "Česká pirátská strana",
    "shortName": "Piráti",
    "sortName": "Piráti",
    "type": "candidate-list"
  },
  {
    "id": "4c66e9de-38dd-4b78-b3ac-f8fbf9c85819",
    "name": "PŘÍSAHA občanské hnutí",
    "shortName": "PŘÍSAHA",
    "sortName": "PŘÍSAHA",
    "type": "candidate-list"
  },
  {
    "id": "e650147c-7d98-4a8f-9d31-4846f9fdb12f",
    "name": "SVOBODNÍ A ŠVÝCARSKÁ DEMOKRACIE",
    "shortName": "Svob+Švýc.dem.",
    "sortName": "Svob+Švýc.dem.",
    "type": "candidate-list"
  },
  {
    "id": "641432f7-07f8-471f-808a-3108940b1d6f",
    "name": "STAČILO! v Ústeckém kraji – KSČM, SOCDEM, ČSNS",
    "shortName": "ČSNS+SOCDE+KSČM",
    "sortName": "ČSNS+SOCDE+KSČM",
    "type": "candidate-list"
  },
  {
    "id": "743aa8ce-ff67-4356-82fb-e5e0d4bbf812",
    "name": "Demokratická strana zelených - ZA PRÁVA ZVÍŘAT",
    "shortName": "DSZ-ZA PR.ZVÍŘ.",
    "sortName": "DSZ-ZA PR.ZVÍŘ.",
    "type": "candidate-list"
  },
  {
    "id": "3fcb6606-d7b4-479c-9529-b1421cb69066",
    "name": "Občanská demokratická strana",
    "shortName": "ODS",
    "sortName": "ODS",
    "type": "candidate-list"
  },
  {
    "id": "951cba08-0fd9-4030-97cb-6a4387e1e541",
    "name": "SPD, Trikolora a PRO",
    "shortName": "SPD+Trikol+PRO",
    "sortName": "SPD+Trikol+PRO",
    "type": "candidate-list"
  },
  {
    "id": "2fac5736-5ddb-441e-b20c-0a725bc32990",
    "name": "STAROSTOVÉ PRO ÚSTECKÝ KRAJ",
    "shortName": "STAN+PRO Zdraví",
    "sortName": "STAN+PRO Zdraví",
    "type": "candidate-list"
  },
  {
    "id": "e4ee9450-8118-4087-9d64-d66c9df5870b",
    "name": "HLAS Regionů",
    "shortName": "USZ+SDSN+SpV+HS",
    "sortName": "USZ+SDSN+SpV+HS",
    "type": "candidate-list"
  },
  {
    "id": "9acfde2f-d769-4bbd-980b-9e55e2bffd5d",
    "name": "Spojenci pro kraj",
    "shortName": "Zel+ED+TOP+JP",
    "sortName": "Zel+ED+TOP+JP",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/62-prostejov/organizations.json
[
  {
    "id": "e8833483-680f-435a-af44-b759327578c8",
    "name": "ANO",
    "sortName": "ANO",
    "shortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "89395259-1fd2-4a28-8a86-537ecf69944f",
    "name": "JaSaN",
    "sortName": "JaSaN",
    "shortName": "JaSaN",
    "type": "candidate-list"
  },
  {
    "id": "46927f39-fffa-44de-aa6b-ee76f53052bf",
    "name": "KDU-ČSL",
    "sortName": "KDU-ČSL",
    "shortName": "KDU-ČSL",
    "type": "candidate-list"
  },
  {
    "id": "03b05c3c-f40e-4e19-a885-bcc911043444",
    "name": "ODS+OPAT",
    "sortName": "ODS+OPAT",
    "shortName": "ODS+OPAT",
    "type": "candidate-list"
  },
  {
    "id": "5cb5d56c-688e-4b55-a801-8a803d939aab",
    "name": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "shortName": "SPD+Trikolora",
    "type": "candidate-list"
  },
  {
    "id": "c520ea72-5d5b-4b91-b170-bea15e884c88",
    "name": "Zelení+STAN+SEN",
    "sortName": "Zelení+STAN+SEN",
    "shortName": "Zelení+STAN+SEN",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/56-breclav/organizations.json
[
  {
    "id": "e8833483-680f-435a-af44-b759327578c8",
    "name": "ANO",
    "sortName": "ANO",
    "shortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "64a0008f-2d59-4a0f-961f-8fa2fd1a7835",
    "name": "KDU+ODS+TOP 09",
    "sortName": "KDU+ODS+TOP 09",
    "shortName": "KDU+ODS+TOP 09",
    "type": "candidate-list"
  },
  {
    "id": "40a4e263-ec72-417a-8e6f-f97297351b13",
    "name": "KSČM",
    "sortName": "KSČM",
    "shortName": "KSČM",
    "type": "candidate-list"
  },
  {
    "id": "a58c608d-34db-40bf-9c0b-7e1de5e39200",
    "name": "Nestranici2024",
    "sortName": "Nestranici2024",
    "shortName": "Nestranici2024",
    "type": "candidate-list"
  },
  {
    "id": "952ed13b-c9ab-44cd-9019-3a19431aa4d9",
    "name": "NOS",
    "sortName": "NOS",
    "shortName": "NOS",
    "type": "candidate-list"
  },
  {
    "id": "14aa404d-35be-421d-aa87-fe6b3e2e7ae6",
    "name": "PŘÍSAHA",
    "sortName": "PŘÍSAHA",
    "shortName": "PŘÍSAHA",
    "type": "candidate-list"
  },
  {
    "id": "758b3394-1927-477c-81bb-4bb4605fd3ef",
    "name": "SOCDEM",
    "sortName": "SOCDEM",
    "shortName": "SOCDEM",
    "type": "candidate-list"
  },
  {
    "id": "5cb5d56c-688e-4b55-a801-8a803d939aab",
    "name": "SPD+Trikolora",
    "sortName": "SPD+Trikolora",
    "shortName": "SPD+Trikolora",
    "type": "candidate-list"
  },
  {
    "id": "15630910-e388-4038-bfeb-04781a6cf2d6",
    "name": "STAN",
    "sortName": "STAN",
    "shortName": "STAN",
    "type": "candidate-list"
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/krajske-2024/9-vysocina/organizations.json
[
  {
    "id": "a8baeebd-1ea3-44a8-8490-a9a90d0d33d1",
    "name": "ANO 2011",
    "shortName": "ANO",
    "sortName": "ANO",
    "type": "candidate-list"
  },
  {
    "id": "b6583cd2-1a3f-41ac-b48d-344ea67341f7",
    "name": "STAČILO!",
    "shortName": "ČSNS+KSČM+ČSSD",
    "sortName": "ČSNS+KSČM+ČSSD",
    "type": "candidate-list"
  },
  {
    "id": "e5b9fb7f-7141-4d35-a1e2-63d7794aebcb",
    "name": "KDU-ČSL",
    "shortName": "KDU-ČSL",
    "sortName": "KDU-ČSL",
    "type": "candidate-list"
  },
  {
    "id": "f1697775-caeb-45b9-ae5c-7498849769f9",
    "name": "MÁ VLAST ČECHY MORAVA SLEZSKO",
    "shortName": "MÁ VLAST ČMS",
    "sortName": "MÁ VLAST ČMS",
    "type": "candidate-list"
  },
  {
    "id": "53157b56-0092-4e3a-92fa-44b212036595",
    "name": "LEPŠÍ ŽIVOT PRO LIDI - minimální MZDA 70.000 Kč, minimální DŮCHOD 50.000 Kč, ZRUŠENÍ daně z nemovitostí, …",
    "shortName": "ND+LŽPL",
    "sortName": "ND+LŽPL",
    "type": "candidate-list"
  },
  {
    "id": "4a98dbe6-794a-4cf2-833c-864d8ed4664e",
    "name": "Nezávislá kandidátka",
    "shortName": "NeKa",
    "sortName": "NeKa",
    "type": "candidate-list"
  },
  {
    "id": "eed8efe7-bdd3-4953-9c98-37c8fbd8aebb",
    "name": "Společně se Starosty pro občany",
    "shortName": "ODS+TOP 09+STO",
    "sortName": "ODS+TOP 09+STO",
    "type": "candidate-list"
  },
  {
    "id": "06b656ea-8c9d-4105-a256-3100a0365d76",
    "name": "Česká pirátská strana",
    "shortName": "Piráti",
    "sortName": "Piráti",
    "type": "candidate-list"
  },
  {
    "id": "9193eaed-79b8-428b-a391-14c2de688da8",
    "name": "STAROSTOVÉ PRO VYSOČINU",
    "shortName": "STAN+SNK ED",
    "sortName": "STAN+SNK ED",
    "type": "candidate-list"
  },
  {
    "id": "f815079d-c679-44d1-8f79-d622ee08bba1",
    "name": "Demokratická strana zelených - ZA PRÁVA ZVÍŘAT",
    "shortName": "DSZ-ZA PR.ZVÍŘ.",
    "sortName": "DSZ-ZA PR.ZVÍŘ.",
    "type": "candidate-list"
  },
  {
    "id": "41a3c037-d090-4ff3-8dd0-eaa95e47a0ee",
    "name": "PŘÍSAHA občanské hnutí",
    "shortName": "PŘÍSAHA",
    "sortName": "PŘÍSAHA",
    "type": "candidate-list"
  },
  {
    "id": "c3417abb-6114-4760-b111-e339110558b5",
    "name": "Sociální demokracie",
    "shortName": "SOCDEM",
    "sortName": "SOCDEM",
    "type": "candidate-list"
  },
  {
    "id": "284b349a-edee-4cb2-9bf7-3e4afe34d0da",
    "name": "SPD, Trikolora a PRO",
    "shortName": "SPD+Trikol+PRO",
    "sortName": "SPD+Trikol+PRO",
    "type": "candidate-list"
  }
]
