=== kalkulacka-one/kalkulacka/packages/schema/schemas/person.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://schema.kalkulacka.one/person.schema.json",
	"title": "Person",
	"description": "A human being",
	"type": "object",
	"properties": {
		"id": {
			"title": "ID",
			"description": "Unique identifier of a person in the format of UUID",
			"type": "string",
			"format": "uuid",
			"examples": ["5ee570e9-fdc6-4af1-8af5-a5e5589c44a6"]
		},
		"name": {
			"title": "Name",
			"description": "Person's preferred full name",
			"type": "string"
		},
		"familyName": {
			"description": "Family name (last name)",
			"type": "string"
		},
		"givenName": {
			"description": "Given name (first name)",
			"type": "string"
		},
		"additionalName": {
			"description": "Additional name (middle name)",
			"type": "string"
		},
		"honorificPrefix": {
			"description": "Honorifics preceding a person's name",
			"type": "string"
		},
		"honorificSuffix": {
			"description": "Honorifics following a person's name",
			"type": "string"
		},
		"sortName": {
			"description": "A name to use in a lexicographically ordered list",
			"type": "string"
		},
		"alternateNames": {
			"description": "Alternate names to use for example in search",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"images": {
			"$ref": "./images.schema.json"
		},
		"memberOf": {
			"title": "Member of",
			"description": "List of organizations a person is a member of",
			"type": "array",
			"minItems": 1,
			"items": {
				"title": "Organization",
				"description": "Reference to an organization",
				"type": "object",
				"properties": {
					"id": {
						"$ref": "./organization.schema.json#/properties/id"
					}
				},
				"unevaluatedProperties": false,
				"required": ["id"]
			}
		}
	},
	"unevaluatedProperties": false,
	"required": ["id"],
	"anyOf": [
		{
			"required": ["name"]
		},
		{
			"required": ["familyName", "givenName"]
		}
	]
}

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/5-chomutov/persons.json
[
  {
    "id": "cc9b4c48-6fbe-458a-beaf-ce0f1016b2aa",
    "name": "Elvíra Hahnová",
    "givenName": "Elvíra",
    "familyName": "Hahnová",
    "sortName": "Hahnová Elvíra",
    "memberOf": [
      {
        "id": "6af5fa71-2a70-430e-9b29-45ead10d7018"
      }
    ]
  },
  {
    "id": "0673157c-b874-4ee2-a328-91c78827e91e",
    "name": "Jiří Kulhánek",
    "givenName": "Jiří",
    "familyName": "Kulhánek",
    "sortName": "Kulhánek Jiří",
    "memberOf": [
      {
        "id": "64a0008f-2d59-4a0f-961f-8fa2fd1a7835"
      }
    ]
  },
  {
    "id": "896fd673-6005-4003-8005-3a5207fad36f",
    "name": "Jaroslav Komínek",
    "givenName": "Jaroslav",
    "familyName": "Komínek",
    "sortName": "Komínek Jaroslav",
    "memberOf": [
      {
        "id": "40a4e263-ec72-417a-8e6f-f97297351b13"
      }
    ]
  },
  {
    "id": "0d2433e9-3f89-47c1-874a-e053dc2317e3",
    "name": "Roman Brand",
    "givenName": "Roman",
    "familyName": "Brand",
    "sortName": "Brand Roman",
    "memberOf": [
      {
        "id": "2380b884-88a5-4282-a772-b8f0ba6feaa0"
      }
    ]
  },
  {
    "id": "92b85465-17e5-48a2-85fb-1e7e77bb44f8",
    "name": "Přemysl Rabas",
    "givenName": "Přemysl",
    "familyName": "Rabas",
    "sortName": "Rabas Přemysl",
    "memberOf": [
      {
        "id": "50e58d59-db2e-4949-a1c8-58cf68bd21f5"
      }
    ]
  },
  {
    "id": "0bdb684e-43d9-45b4-a7d2-1a0153dd70b2",
    "name": "Jiří Smetana",
    "givenName": "Jiří",
    "familyName": "Smetana",
    "sortName": "Smetana Jiří",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "d4580ba9-9dd8-435a-8194-93d1baf46d81",
    "name": "Štefan Drozd",
    "givenName": "Štefan",
    "familyName": "Drozd",
    "sortName": "Drozd Štefan",
    "memberOf": [
      {
        "id": "15630910-e388-4038-bfeb-04781a6cf2d6"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/2-sokolov/persons.json
[
  {
    "id": "7ab1b3b4-3c1a-4e12-bb3a-4f332b5792a5",
    "name": "Jana Mračková Vildumetzová",
    "givenName": "Jana",
    "familyName": "Mračková Vildumetzová",
    "sortName": "Mračková Vildumetzová Jana",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "e2165d3d-fa14-46b1-aa53-63f0e13ca233",
    "name": "Alexandr Terek",
    "givenName": "Alexandr",
    "familyName": "Terek",
    "sortName": "Terek Alexandr",
    "memberOf": [
      {
        "id": "f2e8b77f-f263-448a-b416-9111778c0cf9"
      }
    ]
  },
  {
    "id": "648bca28-284b-49cf-8495-36959aaad846",
    "name": "Josef Vaněk",
    "givenName": "Josef",
    "familyName": "Vaněk",
    "sortName": "Vaněk Josef",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "8584e489-46a9-480e-aa3c-e08e339a069e",
    "name": "Dana Wittnerová",
    "givenName": "Dana",
    "familyName": "Wittnerová",
    "sortName": "Wittnerová Dana",
    "memberOf": [
      {
        "id": "ba98fb1e-3a37-4507-80c5-134cc7c3c9af"
      }
    ]
  },
  {
    "id": "75a2f341-51e9-4ecf-9576-f141af5b83ca",
    "name": "Miroslav Balatka",
    "givenName": "Miroslav",
    "familyName": "Balatka",
    "sortName": "Balatka Miroslav",
    "memberOf": [
      {
        "id": "15630910-e388-4038-bfeb-04781a6cf2d6"
      }
    ]
  },
  {
    "id": "975d4fcf-28af-43a0-a12f-076dd2d5fbe1",
    "name": "Jan Picka",
    "givenName": "Jan",
    "familyName": "Picka",
    "sortName": "Picka Jan",
    "memberOf": [
      {
        "id": "ab95d98f-6ccb-44a5-913c-4ec073f5be44"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/62-prostejov/persons.json
[
  {
    "id": "e389eaa6-a2a9-4da3-b503-c69ddf01d14f",
    "name": "František Jura",
    "givenName": "František",
    "familyName": "Jura",
    "sortName": "Jura František",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "2cf10119-1b81-4d18-8dde-3d8a89e86e96",
    "name": "Miroslav Burget",
    "givenName": "Miroslav",
    "familyName": "Burget",
    "sortName": "Burget Miroslav",
    "memberOf": [
      {
        "id": "89395259-1fd2-4a28-8a86-537ecf69944f"
      }
    ]
  },
  {
    "id": "ed41997d-fbb4-4dd1-9e5a-c2461b44b97b",
    "name": "Hana Pospíšilíková",
    "givenName": "Hana",
    "familyName": "Pospíšilíková",
    "sortName": "Pospíšilíková Hana",
    "memberOf": [
      {
        "id": "46927f39-fffa-44de-aa6b-ee76f53052bf"
      }
    ]
  },
  {
    "id": "8e079344-35c4-4874-bbd2-19afd0c89104",
    "name": "Milada Sokolová",
    "givenName": "Milada",
    "familyName": "Sokolová",
    "sortName": "Sokolová Milada",
    "memberOf": [
      {
        "id": "03b05c3c-f40e-4e19-a885-bcc911043444"
      }
    ]
  },
  {
    "id": "fdadf5dc-e6ab-45bb-abdf-89290dcfe8ac",
    "name": "Pavel Dopita",
    "givenName": "Pavel",
    "familyName": "Dopita",
    "sortName": "Dopita Pavel",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "82d67027-1fdb-4cdf-9008-8e08b49b03fc",
    "name": "Hana Naiclerová",
    "givenName": "Hana",
    "familyName": "Naiclerová",
    "sortName": "Naiclerová Hana",
    "memberOf": [
      {
        "id": "c520ea72-5d5b-4b91-b170-bea15e884c88"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/80-zlin/persons.json
[
  {
    "id": "e09bb6b1-4c02-4236-a362-e6d34e1ede81",
    "name": "Oldřich Hájek",
    "givenName": "Oldřich",
    "familyName": "Hájek",
    "sortName": "Hájek Oldřich",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "c018060f-957b-4ff5-8593-cba753edb0e2",
    "name": "Patrik Kunčar",
    "givenName": "Patrik",
    "familyName": "Kunčar",
    "sortName": "Kunčar Patrik",
    "memberOf": [
      {
        "id": "46927f39-fffa-44de-aa6b-ee76f53052bf"
      }
    ]
  },
  {
    "id": "85077d27-8b6a-4c19-a0a4-2c43d294cf01",
    "name": "Jana Juřenčáková",
    "givenName": "Jana",
    "familyName": "Juřenčáková",
    "sortName": "Juřenčáková Jana",
    "memberOf": [
      {
        "id": "6f007ce1-2275-4abc-b38f-65913d78f7e6"
      }
    ]
  },
  {
    "id": "ed0451b2-ebe8-495e-a61e-c1a73602f967",
    "name": "David Rumpík",
    "givenName": "David",
    "familyName": "Rumpík",
    "sortName": "Rumpík David",
    "memberOf": [
      {
        "id": "8331b263-fda5-459d-b28c-ddb84f281963"
      }
    ]
  },
  {
    "id": "d645041f-4036-4890-a275-4bf3b23be6a4",
    "name": "Barbora Fojtáchová",
    "givenName": "Barbora",
    "familyName": "Fojtáchová",
    "sortName": "Fojtáchová Barbora",
    "memberOf": [
      {
        "id": "37a912ea-5bb0-476f-a124-6729ba67cc7e"
      }
    ]
  },
  {
    "id": "6887a248-e299-4438-b92d-61e9040ef96b",
    "name": "Zbyněk Ziggy Horváth",
    "givenName": "Zbyněk Ziggy",
    "familyName": "Horváth",
    "sortName": "Horváth Zbyněk Ziggy",
    "memberOf": [
      {
        "id": "15630910-e388-4038-bfeb-04781a6cf2d6"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/47-nachod/persons.json
[
  {
    "id": "e21e451b-34e2-4bdf-88c3-9caae0746efc",
    "name": "Jan Borůvka",
    "givenName": "Jan",
    "familyName": "Borůvka",
    "sortName": "Borůvka Jan",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "0230ed3c-4609-4ae5-a593-5381f542c617",
    "name": "Martin Červíček",
    "givenName": "Martin",
    "familyName": "Červíček",
    "sortName": "Červíček Martin",
    "memberOf": [
      {
        "id": "f87f4d6b-f2d5-49fa-8a38-2757be7d3309"
      }
    ]
  },
  {
    "id": "9f8a9461-a9b5-4b71-ae90-d9d8af113385",
    "name": "Tomáš Magnusek",
    "givenName": "Tomáš",
    "familyName": "Magnusek",
    "sortName": "Magnusek Tomáš",
    "memberOf": [
      {
        "id": "80121f2b-b391-4a27-be2a-db2699e59b48"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/17-praha-12/persons.json
[
  {
    "id": "b1d38a84-c36b-4748-aca8-7ae54ae9eade",
    "name": "Boris Šťastný",
    "givenName": "Boris",
    "familyName": "Šťastný",
    "sortName": "Šťastný Boris",
    "memberOf": [
      {
        "id": "081afd8b-19c0-456a-a532-c53385383e0a"
      }
    ]
  },
  {
    "id": "41e05602-1ac3-4252-9b20-618e41898819",
    "name": "Pavel Fischer",
    "givenName": "Pavel",
    "familyName": "Fischer",
    "sortName": "Fischer Pavel",
    "memberOf": [
      {
        "id": "29fcc360-87ef-4800-ac24-b1bc2b2057bd"
      }
    ]
  },
  {
    "id": "d8c0b88e-79df-4037-a433-dd1165068bdb",
    "name": "Eva Tylová",
    "givenName": "Eva",
    "familyName": "Tylová",
    "sortName": "Tylová Eva",
    "memberOf": [
      {
        "id": "31ef10ae-3173-4397-a4fd-95c5ff2f1361"
      }
    ]
  },
  {
    "id": "66436ce1-38f9-4c31-8278-7e2216e5d8e2",
    "name": "Petr Hůla",
    "givenName": "Petr",
    "familyName": "Hůla",
    "sortName": "Hůla Petr",
    "memberOf": [
      {
        "id": "758b3394-1927-477c-81bb-4bb4605fd3ef"
      }
    ]
  },
  {
    "id": "9fd21aa5-09f2-412e-b250-d1240fcb8ad3",
    "name": "Milan Urban",
    "givenName": "Milan",
    "familyName": "Urban",
    "sortName": "Urban Milan",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "fe8b8136-b9cd-4983-ae42-fd77d9b31e65",
    "name": "Pynelopi Cimprichová",
    "givenName": "Pynelopi",
    "familyName": "Cimprichová",
    "sortName": "Cimprichová Pynelopi",
    "memberOf": [
      {
        "id": "7dfbba65-9e0f-4654-bf9b-81eca8783f8f"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/59-brno-mesto/persons.json
[
  {
    "id": "b026dca0-d275-45c7-85e1-ae561e549f13",
    "name": "Marie Jílková",
    "givenName": "Marie",
    "familyName": "Jílková",
    "sortName": "Jílková Marie",
    "memberOf": [
      {
        "id": "46927f39-fffa-44de-aa6b-ee76f53052bf"
      }
    ]
  },
  {
    "id": "a79d37d3-ed01-4ebe-8bc4-5769eaac9632",
    "name": "Karin Podivinská",
    "givenName": "Karin",
    "familyName": "Podivinská",
    "sortName": "Podivinská Karin",
    "memberOf": [
      {
        "id": "de9476eb-0063-47c0-9ada-d8c3fd0609f3"
      }
    ]
  },
  {
    "id": "4d3885c5-001e-4ee7-b030-9d1b8bbd3dc7",
    "name": "Petr Kovač",
    "givenName": "Petr",
    "familyName": "Kovač",
    "sortName": "Kovač Petr",
    "memberOf": [
      {
        "id": "ff1877fc-95a7-430a-bb90-2088a9983f9d"
      }
    ]
  },
  {
    "id": "d1308825-e3ca-4d1d-8085-e95b68ff4224",
    "name": "Tomáš Skřička",
    "givenName": "Tomáš",
    "familyName": "Skřička",
    "sortName": "Skřička Tomáš",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "9e65d0eb-42a3-4967-8edf-46850ec90466",
    "name": "Libor Zabloudil",
    "givenName": "Libor",
    "familyName": "Zabloudil",
    "sortName": "Zabloudil Libor",
    "memberOf": [
      {
        "id": "15630910-e388-4038-bfeb-04781a6cf2d6"
      }
    ]
  },
  {
    "id": "ddda193a-853a-458a-b8be-912324329def",
    "name": "Michal Janda",
    "givenName": "Michal",
    "familyName": "Janda",
    "sortName": "Janda Michal",
    "memberOf": [
      {
        "id": "6797d805-5e00-4f26-acb5-a61f8b4895ba"
      }
    ]
  },
  {
    "id": "de97eae9-2dc1-4ef3-88e8-40c7726d60b0",
    "name": "Břetislav Rychlík",
    "givenName": "Břetislav",
    "familyName": "Rychlík",
    "sortName": "Rychlík Břetislav",
    "memberOf": [
      {
        "id": "b79dfa80-b1a3-4c13-bf44-4421f32d6c17"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/35-jablonec-nad-nisou/persons.json
[
  {
    "id": "57433329-75ff-4554-b1a5-60459387cd8b",
    "name": "Milan Kroupa",
    "givenName": "Milan",
    "familyName": "Kroupa",
    "sortName": "Kroupa Milan",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "7a19d653-8ab2-4b81-9b3f-066cad58a509",
    "name": "Tomáš Vašíček",
    "givenName": "Tomáš",
    "familyName": "Vašíček",
    "sortName": "Vašíček Tomáš",
    "memberOf": [
      {
        "id": "a32089e0-5fda-44fb-b12a-c97139bdb785"
      }
    ]
  },
  {
    "id": "5abb91f9-b78b-4efb-9e50-d9829b86ec16",
    "name": "Vít Němeček",
    "givenName": "Vít",
    "familyName": "Němeček",
    "sortName": "Němeček Vít",
    "memberOf": [
      {
        "id": "64a0008f-2d59-4a0f-961f-8fa2fd1a7835"
      }
    ]
  },
  {
    "id": "6b59aa30-5ec6-45c2-8252-6a9ff276e0dd",
    "name": "Michaela Tejmlová",
    "givenName": "Michaela",
    "familyName": "Tejmlová",
    "sortName": "Tejmlová Michaela",
    "memberOf": [
      {
        "id": "50e58d59-db2e-4949-a1c8-58cf68bd21f5"
      }
    ]
  },
  {
    "id": "10517a10-ec12-43c8-b3c2-ba87bc03b140",
    "name": "Lena Mlejnková",
    "givenName": "Lena",
    "familyName": "Mlejnková",
    "sortName": "Mlejnková Lena",
    "memberOf": [
      {
        "id": "ff170d83-5e25-485e-979d-a5d58081d490"
      }
    ]
  },
  {
    "id": "a760cfdc-21a8-4083-b6eb-30b9f5100017",
    "name": "Michal Švarc",
    "givenName": "Michal",
    "familyName": "Švarc",
    "sortName": "Švarc Michal",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  }
]
