=== kalkulacka-one/kalkulacka/packages/schema/schemas/person.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://schema.kalkulacka.one/person.schema.json",
	"title": "Person",
	"description": "A human being",
	"type": "object",
	"properties": {
		"id": {
			"title": "ID",
			"description": "Unique identifier of a person in the format of UUID",
			"type": "string",
			"format": "uuid",
			"examples": ["5ee570e9-fdc6-4af1-8af5-a5e5589c44a6"]
		},
		"name": {
			"title": "Name",
			"description": "Person's preferred full name",
			"type": "string"
		},
		"familyName": {
			"description": "Family name (last name)",
			"type": "string"
		},
		"givenName": {
			"description": "Given name (first name)",
			"type": "string"
		},
		"additionalName": {
			"description": "Additional name (middle name)",
			"type": "string"
		},
		"honorificPrefix": {
			"description": "Honorifics preceding a person's name",
			"type": "string"
		},
		"honorificSuffix": {
			"description": "Honorifics following a person's name",
			"type": "string"
		},
		"sortName": {
			"description": "A name to use in a lexicographically ordered list",
			"type": "string"
		},
		"alternateNames": {
			"description": "Alternate names to use for example in search",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"images": {
			"$ref": "./images.schema.json"
		},
		"memberOf": {
			"title": "Member of",
			"description": "List of organizations a person is a member of",
			"type": "array",
			"minItems": 1,
			"items": {
				"title": "Organization",
				"description": "Reference to an organization",
				"type": "object",
				"properties": {
					"id": {
						"$ref": "./organization.schema.json#/properties/id"
					}
				},
				"unevaluatedProperties": false,
				"required": ["id"]
			}
		}
	},
	"unevaluatedProperties": false,
	"required": ["id"],
	"anyOf": [
		{
			"required": ["name"]
		},
		{
			"required": ["familyName", "givenName"]
		}
	]
}

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/50-svitavy/persons.json
[
  {
    "id": "643f3046-25b9-4a12-87a1-2d2084d63030",
    "name": "Milena Míčová",
    "givenName": "Milena",
    "familyName": "Míčová",
    "sortName": "Míčová Milena",
    "memberOf": [
      {
        "id": "89395259-1fd2-4a28-8a86-537ecf69944f"
      }
    ]
  },
  {
    "id": "759f0603-ccd6-4861-b524-df62d067b95d",
    "name": "David Šimek",
    "givenName": "David",
    "familyName": "Šimek",
    "sortName": "Šimek David",
    "memberOf": [
      {
        "id": "aa886e40-4ca9-4d65-b909-4a15928e1861"
      }
    ]
  },
  {
    "id": "291c33d8-9ad0-40aa-9e02-9c9c7bf605c3",
    "name": "Pavel Severa",
    "givenName": "Pavel",
    "familyName": "Severa",
    "sortName": "Severa Pavel",
    "memberOf": [
      {
        "id": "8331b263-fda5-459d-b28c-ddb84f281963"
      }
    ]
  },
  {
    "id": "2bfd2b1c-3b70-43e2-b229-2e7e882efe48",
    "name": "Michal Kortyš",
    "givenName": "Michal",
    "familyName": "Kortyš",
    "sortName": "Kortyš Michal",
    "memberOf": [
      {
        "id": "f87f4d6b-f2d5-49fa-8a38-2757be7d3309"
      }
    ]
  },
  {
    "id": "fa253860-e699-4478-b637-9a4ee1229f01",
    "name": "Pavel Havíř",
    "givenName": "Pavel",
    "familyName": "Havíř",
    "sortName": "Havíř Pavel",
    "memberOf": [
      {
        "id": "5c2df6a6-1511-4f98-94eb-95dacef147d6"
      }
    ]
  },
  {
    "id": "e1819490-b0ec-440b-902f-305108290cfa",
    "name": "Hynek Blaško",
    "givenName": "Hynek",
    "familyName": "Blaško",
    "sortName": "Blaško Hynek",
    "memberOf": [
      {
        "id": "4f390d39-afd6-4aae-a854-842dd8148163"
      }
    ]
  },
  {
    "id": "b21dc167-937d-4b57-9235-86531a23a613",
    "name": "Petr Štěpánek",
    "givenName": "Petr",
    "familyName": "Štěpánek",
    "sortName": "Štěpánek Petr",
    "memberOf": [
      {
        "id": "1dbf4591-b049-4b3e-97c0-73f31db974d1"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/53-trebic/persons.json
[
  {
    "id": "bac60127-c4ac-4fb4-a3f6-60fab7c8e0dc",
    "name": "Drahoslav Ryba",
    "givenName": "Drahoslav",
    "familyName": "Ryba",
    "sortName": "Ryba Drahoslav",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "0064fe03-a2ec-4c38-83e1-3738466482ea",
    "name": "Luděk Růžička",
    "givenName": "Luděk",
    "familyName": "Růžička",
    "sortName": "Růžička Luděk",
    "memberOf": [
      {
        "id": "34af5333-7e1b-418e-8145-1ff2d2b874a5"
      }
    ]
  },
  {
    "id": "6555fed3-6a63-48da-a378-5f5288e0e847",
    "name": "Petr Chňoupek",
    "givenName": "Petr",
    "familyName": "Chňoupek",
    "sortName": "Chňoupek Petr",
    "memberOf": [
      {
        "id": "599fa7bf-3231-41b0-8a56-cd50b602f07a"
      }
    ]
  },
  {
    "id": "d1a93f79-8a87-47fd-b815-ed0a450d5326",
    "name": "Zdeněk Ryšavý",
    "givenName": "Zdeněk",
    "familyName": "Ryšavý",
    "sortName": "Ryšavý Zdeněk",
    "memberOf": [
      {
        "id": "758b3394-1927-477c-81bb-4bb4605fd3ef"
      }
    ]
  },
  {
    "id": "29682a80-9ab5-48ba-8414-a834b5cc2a01",
    "name": "Václav Lhotský",
    "givenName": "Václav",
    "familyName": "Lhotský",
    "sortName": "Lhotský Václav",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "05c0ea58-4f2b-4080-b272-108472da1677",
    "name": "Hana Žáková",
    "givenName": "Hana",
    "familyName": "Žáková",
    "sortName": "Žáková Hana",
    "memberOf": [
      {
        "id": "15630910-e388-4038-bfeb-04781a6cf2d6"
      }
    ]
  },
  {
    "id": "53acb24a-10e6-41b5-ba07-b01f2565c93c",
    "name": "Jaroslav Turánek",
    "givenName": "Jaroslav",
    "familyName": "Turánek",
    "sortName": "Turánek Jaroslav",
    "memberOf": [
      {
        "id": "7dfbba65-9e0f-4654-bf9b-81eca8783f8f"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/74-karvina/persons.json
[
  {
    "id": "07acfc87-087c-4c02-9b57-516ae4e9d2b8",
    "name": "Karel Volný",
    "givenName": "Karel",
    "familyName": "Volný",
    "sortName": "Volný Karel",
    "memberOf": [
      {
        "id": "6af5fa71-2a70-430e-9b29-45ead10d7018"
      }
    ]
  },
  {
    "id": "61dc44a9-eb2d-44fb-97d9-7aac040a0ecd",
    "name": "Bohuslav Niemiec",
    "givenName": "Bohuslav",
    "familyName": "Niemiec",
    "sortName": "Niemiec Bohuslav",
    "memberOf": [
      {
        "id": "64a0008f-2d59-4a0f-961f-8fa2fd1a7835"
      }
    ]
  },
  {
    "id": "0d3b241b-56d6-4f73-a1cb-326699f3943d",
    "name": "Petr Vícha",
    "givenName": "Petr",
    "familyName": "Vícha",
    "sortName": "Vícha Petr",
    "memberOf": [
      {
        "id": "758b3394-1927-477c-81bb-4bb4605fd3ef"
      }
    ]
  },
  {
    "id": "99efa29a-29d0-4f36-a265-fff2c21eb598",
    "name": "Pavel Staněk",
    "givenName": "Pavel",
    "familyName": "Staněk",
    "sortName": "Staněk Pavel",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "fbaa11d0-f996-4160-853d-a615a4b1dc42",
    "name": "Karel Světnička",
    "givenName": "Karel",
    "familyName": "Světnička",
    "sortName": "Světnička Karel",
    "memberOf": [
      {
        "id": "7dfbba65-9e0f-4654-bf9b-81eca8783f8f"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/44-chrudim/persons.json
[
  {
    "id": "49f073ad-9c6c-40ee-b9fb-8339766f9606",
    "name": "Vladimír Slávka",
    "givenName": "Vladimír",
    "familyName": "Slávka",
    "sortName": "Slávka Vladimír",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "15bf2434-3580-4fad-8294-b8684bb8b814",
    "name": "Roman Málek",
    "givenName": "Roman",
    "familyName": "Málek",
    "sortName": "Málek Roman",
    "memberOf": [
      {
        "id": "a7998914-b3ad-4567-8c14-3e23f3fbb2b2"
      }
    ]
  },
  {
    "id": "f6f50a94-5f98-45da-b224-cc9dc60da37c",
    "name": "Jan Tecl",
    "givenName": "Jan",
    "familyName": "Tecl",
    "sortName": "Tecl Jan",
    "memberOf": [
      {
        "id": "f87f4d6b-f2d5-49fa-8a38-2757be7d3309"
      }
    ]
  },
  {
    "id": "c18a5fd1-a480-4868-afd5-bf55084d05e6",
    "name": "Milan Chaloupecký",
    "givenName": "Milan",
    "familyName": "Chaloupecký",
    "sortName": "Chaloupecký Milan",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "84518935-e166-43f0-84d7-71aec2ef3f12",
    "name": "Miroslav Krčil",
    "givenName": "Miroslav",
    "familyName": "Krčil",
    "sortName": "Krčil Miroslav",
    "memberOf": [
      {
        "id": "c52430ee-d000-4c80-9447-e9e7f5c2fe59"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/68-opava/persons.json
[
  {
    "id": "8f87b234-fe42-41e3-a5cf-750680fb37c4",
    "name": "Tomáš Navrátil",
    "givenName": "Tomáš",
    "familyName": "Navrátil",
    "sortName": "Navrátil Tomáš",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "25f143ad-c241-4aaf-bd53-890507215b91",
    "name": "Bronislav Sedláček",
    "givenName": "Bronislav",
    "familyName": "Sedláček",
    "sortName": "Sedláček Bronislav",
    "memberOf": [
      {
        "id": "89395259-1fd2-4a28-8a86-537ecf69944f"
      }
    ]
  },
  {
    "id": "d0a5e8d1-0f16-40c5-8ef3-4604dff377d3",
    "name": "Herbert Pavera",
    "givenName": "Herbert",
    "familyName": "Pavera",
    "sortName": "Pavera Herbert",
    "memberOf": [
      {
        "id": "64a0008f-2d59-4a0f-961f-8fa2fd1a7835"
      }
    ]
  },
  {
    "id": "c3a69fa8-7254-4a62-91fa-e7a2e0055f82",
    "name": "Brigita Bilíková",
    "givenName": "Brigita",
    "familyName": "Bilíková",
    "sortName": "Bilíková Brigita",
    "memberOf": [
      {
        "id": "966d63f4-4986-4345-9c8e-7a9fbc66c37b"
      }
    ]
  },
  {
    "id": "1b31b9e9-d0fc-4e31-a7f4-3111adbf4f5a",
    "name": "Vladimír Tancík",
    "givenName": "Vladimír",
    "familyName": "Tancík",
    "sortName": "Tancík Vladimír",
    "memberOf": [
      {
        "id": "8331b263-fda5-459d-b28c-ddb84f281963"
      }
    ]
  },
  {
    "id": "b252b283-f3b9-41c7-b75f-53f7fe15a4f7",
    "name": "René Černohorský",
    "givenName": "René",
    "familyName": "Černohorský",
    "sortName": "Černohorský René",
    "memberOf": [
      {
        "id": "758b3394-1927-477c-81bb-4bb4605fd3ef"
      }
    ]
  },
  {
    "id": "a9e426e4-87a4-45f7-909e-5c05ccd24e28",
    "name": "Zita Calabri",
    "givenName": "Zita",
    "familyName": "Calabri",
    "sortName": "Calabri Zita",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "fb158169-85dd-4ac8-b9bc-530696b8219f",
    "name": "Michael Rataj",
    "givenName": "Michael",
    "familyName": "Rataj",
    "sortName": "Rataj Michael",
    "memberOf": [
      {
        "id": "14976b4e-8cc6-4d06-8c42-da46665ebe03"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/77-vsetin/persons.json
[
  {
    "id": "808b2cdc-928e-4a86-bcdb-3e108af611b9",
    "name": "Yvona Wojaczková",
    "givenName": "Yvona",
    "familyName": "Wojaczková",
    "sortName": "Wojaczková Yvona",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "3b4ae139-b29d-47a2-8e33-f88a597640b1",
    "name": "Jiří Čunek",
    "givenName": "Jiří",
    "familyName": "Čunek",
    "sortName": "Čunek Jiří",
    "memberOf": [
      {
        "id": "46927f39-fffa-44de-aa6b-ee76f53052bf"
      }
    ]
  },
  {
    "id": "9f289794-eaa0-47ad-aa04-aa8e6ceaeffc",
    "name": "Robert Hampl",
    "givenName": "Robert",
    "familyName": "Hampl",
    "sortName": "Hampl Robert",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/29-litomerice/persons.json
[
  {
    "id": "3a702fd3-bdcb-42a3-bd7e-24627479b1d4",
    "name": "Ondřej Štěrba",
    "givenName": "Ondřej",
    "familyName": "Štěrba",
    "sortName": "Štěrba Ondřej",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "aa7954e0-6faa-45c6-8f64-e27a1067ec44",
    "name": "Jan Skalický",
    "givenName": "Jan",
    "familyName": "Skalický",
    "sortName": "Skalický Jan",
    "memberOf": [
      {
        "id": "bc382abd-a642-43b9-b64e-0ca563ac4ca3"
      }
    ]
  },
  {
    "id": "4003248e-230e-4097-92cf-a0b3946672ec",
    "name": "Vladimír Vlk",
    "givenName": "Vladimír",
    "familyName": "Vlk",
    "sortName": "Vlk Vladimír",
    "memberOf": [
      {
        "id": "6af5fa71-2a70-430e-9b29-45ead10d7018"
      }
    ]
  },
  {
    "id": "ae18e0d7-098c-48ea-8838-ec3df6eb6fdc",
    "name": "Ladislav Chlupáč",
    "givenName": "Ladislav",
    "familyName": "Chlupáč",
    "sortName": "Chlupáč Ladislav",
    "memberOf": [
      {
        "id": "64a0008f-2d59-4a0f-961f-8fa2fd1a7835"
      }
    ]
  },
  {
    "id": "c31d09cb-758b-4862-916a-ed554dac6fa1",
    "name": "Miroslav Jiránek",
    "givenName": "Miroslav",
    "familyName": "Jiránek",
    "sortName": "Jiránek Miroslav",
    "memberOf": [
      {
        "id": "fac96e1b-54cc-4cc0-840e-9443f154c03f"
      }
    ]
  },
  {
    "id": "4ec18352-1d18-41ee-a3bc-e8ba729a4bf9",
    "name": "Ilja Baudyš",
    "givenName": "Ilja",
    "familyName": "Baudyš",
    "sortName": "Baudyš Ilja",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "5a9b98e0-d663-40e7-b4f2-e0c5e40f9848",
    "name": "Petr Liška",
    "givenName": "Petr",
    "familyName": "Liška",
    "sortName": "Liška Petr",
    "memberOf": [
      {
        "id": "15630910-e388-4038-bfeb-04781a6cf2d6"
      }
    ]
  },
  {
    "id": "d68c8fc9-8547-4b66-9086-0ba900036ebc",
    "name": "Martin Kratochvíl",
    "givenName": "Martin",
    "familyName": "Kratochvíl",
    "sortName": "Kratochvíl Martin",
    "memberOf": [
      {
        "id": "6797d805-5e00-4f26-acb5-a61f8b4895ba"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/32-teplice/persons.json
[
  {
    "id": "facd4259-3acf-4f51-9c1c-786e40c9526a",
    "name": "Jan Schiller",
    "givenName": "Jan",
    "familyName": "Schiller",
    "sortName": "Schiller Jan",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "3b795f11-404c-4751-95a2-17c1099194c2",
    "name": "Ivan Vinický",
    "givenName": "Ivan",
    "familyName": "Vinický",
    "sortName": "Vinický Ivan",
    "memberOf": [
      {
        "id": "6af5fa71-2a70-430e-9b29-45ead10d7018"
      }
    ]
  },
  {
    "id": "45a5f383-d4de-4841-a483-e6a6ad561f9c",
    "name": "Tomáš Vandas",
    "givenName": "Tomáš",
    "familyName": "Vandas",
    "sortName": "Vandas Tomáš",
    "memberOf": [
      {
        "id": "c2a3330d-26fb-4c9b-bb22-29697e08da9c"
      }
    ]
  },
  {
    "id": "2eb6e505-7149-4cdb-bf4f-a83f9bd26591",
    "name": "Hynek Hanza",
    "givenName": "Hynek",
    "familyName": "Hanza",
    "sortName": "Hanza Hynek",
    "memberOf": [
      {
        "id": "f87f4d6b-f2d5-49fa-8a38-2757be7d3309"
      }
    ]
  },
  {
    "id": "d3617e79-3008-4a9c-b87a-2dd8f42ca65a",
    "name": "Jiří Řehák",
    "givenName": "Jiří",
    "familyName": "Řehák",
    "sortName": "Řehák Jiří",
    "memberOf": [
      {
        "id": "50e58d59-db2e-4949-a1c8-58cf68bd21f5"
      }
    ]
  },
  {
    "id": "46644c31-036e-4c64-ab6d-98a4e01069ae",
    "name": "Zdeněk Žák",
    "givenName": "Zdeněk",
    "familyName": "Žák",
    "sortName": "Žák Zdeněk",
    "memberOf": [
      {
        "id": "4f390d39-afd6-4aae-a854-842dd8148163"
      }
    ]
  }
]
