=== kalkulacka-one/kalkulacka/packages/schema/schemas/person.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://schema.kalkulacka.one/person.schema.json",
	"title": "Person",
	"description": "A human being",
	"type": "object",
	"properties": {
		"id": {
			"title": "ID",
			"description": "Unique identifier of a person in the format of UUID",
			"type": "string",
			"format": "uuid",
			"examples": ["5ee570e9-fdc6-4af1-8af5-a5e5589c44a6"]
		},
		"name": {
			"title": "Name",
			"description": "Person's preferred full name",
			"type": "string"
		},
		"familyName": {
			"description": "Family name (last name)",
			"type": "string"
		},
		"givenName": {
			"description": "Given name (first name)",
			"type": "string"
		},
		"additionalName": {
			"description": "Additional name (middle name)",
			"type": "string"
		},
		"honorificPrefix": {
			"description": "Honorifics preceding a person's name",
			"type": "string"
		},
		"honorificSuffix": {
			"description": "Honorifics following a person's name",
			"type": "string"
		},
		"sortName": {
			"description": "A name to use in a lexicographically ordered list",
			"type": "string"
		},
		"alternateNames": {
			"description": "Alternate names to use for example in search",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"images": {
			"$ref": "./images.schema.json"
		},
		"memberOf": {
			"title": "Member of",
			"description": "List of organizations a person is a member of",
			"type": "array",
			"minItems": 1,
			"items": {
				"title": "Organization",
				"description": "Reference to an organization",
				"type": "object",
				"properties": {
					"id": {
						"$ref": "./organization.schema.json#/properties/id"
					}
				},
				"unevaluatedProperties": false,
				"required": ["id"]
			}
		}
	},
	"unevaluatedProperties": false,
	"required": ["id"],
	"anyOf": [
		{
			"required": ["name"]
		},
		{
			"required": ["familyName", "givenName"]
		}
	]
}

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/71-ostrava-mesto/persons.json
[
  {
    "id": "7104a36f-25df-4dda-b7af-8a2ceeaf1db4",
    "name": "Martin Bednář",
    "givenName": "Martin",
    "familyName": "Bednář",
    "sortName": "Bednář Martin",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "76cdcd73-5338-4838-ae39-3f5d8034dec3",
    "name": "Leo Luzar",
    "givenName": "Leo",
    "familyName": "Luzar",
    "sortName": "Luzar Leo",
    "memberOf": [
      {
        "id": "bc382abd-a642-43b9-b64e-0ca563ac4ca3"
      }
    ]
  },
  {
    "id": "7feca3e1-f861-4d22-a7a9-dfff913a7de3",
    "name": "Leopold Sulovský",
    "givenName": "Leopold",
    "familyName": "Sulovský",
    "sortName": "Sulovský Leopold",
    "memberOf": [
      {
        "id": "20a54dd5-96f0-4740-b7e2-67f621d32715"
      }
    ]
  },
  {
    "id": "104ca231-786c-462b-b432-c975913f655b",
    "name": "Štefan Režný",
    "givenName": "Štefan",
    "familyName": "Režný",
    "sortName": "Režný Štefan",
    "memberOf": [
      {
        "id": "e2e60e7a-5165-40e8-a233-068db4e79888"
      }
    ]
  },
  {
    "id": "4d7250e6-8c3b-416e-8354-12881e8a7eec",
    "name": "Marie Malcharová",
    "givenName": "Marie",
    "familyName": "Malcharová",
    "sortName": "Malcharová Marie",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "e7efc67c-84da-4312-86f4-b8ffa630b5b0",
    "name": "Liana Janáčková",
    "givenName": "Liana",
    "familyName": "Janáčková",
    "sortName": "Janáčková Liana",
    "memberOf": [
      {
        "id": "6797d805-5e00-4f26-acb5-a61f8b4895ba"
      }
    ]
  },
  {
    "id": "457ed732-fd0f-4217-bb0c-cb65e757293b",
    "name": "Radoslav Štědroň",
    "givenName": "Radoslav",
    "familyName": "Štědroň",
    "sortName": "Štědroň Radoslav",
    "memberOf": [
      {
        "id": "7dfbba65-9e0f-4654-bf9b-81eca8783f8f"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/11-domazlice/persons.json
[
  {
    "id": "14f9fccc-eebb-400a-8c64-a12f6c0ea0a1",
    "name": "Jan Látka",
    "givenName": "Jan",
    "familyName": "Látka",
    "sortName": "Látka Jan",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "93d56e99-6b3e-431f-b1fa-9565185e2a3b",
    "name": "Stanislav Antoš",
    "givenName": "Stanislav",
    "familyName": "Antoš",
    "sortName": "Antoš Stanislav",
    "memberOf": [
      {
        "id": "7cbe01ba-db6b-4969-a91c-68ff4e6c3f2f"
      }
    ]
  },
  {
    "id": "b80bdce2-4ce9-4d19-a523-770141e71d4b",
    "name": "Ivan Maštálka",
    "givenName": "Ivan",
    "familyName": "Maštálka",
    "sortName": "Maštálka Ivan",
    "memberOf": [
      {
        "id": "40a4e263-ec72-417a-8e6f-f97297351b13"
      }
    ]
  },
  {
    "id": "81db3837-e0d9-4ed4-8cd2-c420b9cd16a5",
    "name": "Robert Baxa",
    "givenName": "Robert",
    "familyName": "Baxa",
    "sortName": "Baxa Robert",
    "memberOf": [
      {
        "id": "8331b263-fda5-459d-b28c-ddb84f281963"
      }
    ]
  },
  {
    "id": "8b055a20-c679-4c5b-ac92-2409e041bb48",
    "name": "Vladislav Vilímec",
    "givenName": "Vladislav",
    "familyName": "Vilímec",
    "sortName": "Vilímec Vladislav",
    "memberOf": [
      {
        "id": "f87f4d6b-f2d5-49fa-8a38-2757be7d3309"
      }
    ]
  },
  {
    "id": "17da4353-7c56-4461-b0a9-74f23529a262",
    "name": "Jan Janda",
    "givenName": "Jan",
    "familyName": "Janda",
    "sortName": "Janda Jan",
    "memberOf": [
      {
        "id": "fac96e1b-54cc-4cc0-840e-9443f154c03f"
      }
    ]
  },
  {
    "id": "92b29701-f7ba-4f98-85eb-c962d73c75a4",
    "name": "Václav Sladký",
    "givenName": "Václav",
    "familyName": "Sladký",
    "sortName": "Sladký Václav",
    "memberOf": [
      {
        "id": "758b3394-1927-477c-81bb-4bb4605fd3ef"
      }
    ]
  },
  {
    "id": "20ad9dc2-f7a4-4762-985e-7556a7db9b71",
    "name": "Ján Ridzoň",
    "givenName": "Ján",
    "familyName": "Ridzoň",
    "sortName": "Ridzoň Ján",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "a4601fcb-1c9f-4bad-968f-2580e39a95be",
    "name": "Libor Picka",
    "givenName": "Libor",
    "familyName": "Picka",
    "sortName": "Picka Libor",
    "memberOf": [
      {
        "id": "15630910-e388-4038-bfeb-04781a6cf2d6"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/8-rokycany/persons.json
[
  {
    "id": "34b0490a-8576-4698-9246-0dbd4c89aa8a",
    "name": "Petr Vanka",
    "givenName": "Petr",
    "familyName": "Vanka",
    "sortName": "Vanka Petr",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "721a4ee6-3d49-4255-baf5-2f7acb60bd1d",
    "name": "Tomáš Rada",
    "givenName": "Tomáš",
    "familyName": "Rada",
    "sortName": "Rada Tomáš",
    "memberOf": [
      {
        "id": "7cbe01ba-db6b-4969-a91c-68ff4e6c3f2f"
      }
    ]
  },
  {
    "id": "6f1638a4-4715-4eea-a0b6-96bc23d61070",
    "name": "Pavel Karpíšek",
    "givenName": "Pavel",
    "familyName": "Karpíšek",
    "sortName": "Karpíšek Pavel",
    "memberOf": [
      {
        "id": "46ef04cd-61f7-49cc-8f7a-169995873fe4"
      }
    ]
  },
  {
    "id": "eb433112-c76e-4921-aedb-5548befaee66",
    "name": "Jaromír Pěnkava",
    "givenName": "Jaromír",
    "familyName": "Pěnkava",
    "sortName": "Pěnkava Jaromír",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "d15b9255-f4e2-4b70-8aed-8c5ac7d1ed35",
    "name": "Miroslav Kroc",
    "givenName": "Miroslav",
    "familyName": "Kroc",
    "sortName": "Kroc Miroslav",
    "memberOf": [
      {
        "id": "15630910-e388-4038-bfeb-04781a6cf2d6"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/20-praha-4/persons.json
[
  {
    "id": "fad8d045-0604-443b-b534-ed489b26af9d",
    "name": "Josef Svoboda",
    "givenName": "Josef",
    "familyName": "Svoboda",
    "sortName": "Svoboda Josef",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "13af6cb5-2d14-478b-b071-9a4c37578f6e",
    "name": "Vladimíra Vítová",
    "givenName": "Vladimíra",
    "familyName": "Vítová",
    "sortName": "Vítová Vladimíra",
    "memberOf": [
      {
        "id": "a32089e0-5fda-44fb-b12a-c97139bdb785"
      }
    ]
  },
  {
    "id": "5a16a080-801e-4903-80c1-737960c14196",
    "name": "Pavel Sehnal",
    "givenName": "Pavel",
    "familyName": "Sehnal",
    "sortName": "Sehnal Pavel",
    "memberOf": [
      {
        "id": "a32089e0-5fda-44fb-b12a-c97139bdb785"
      }
    ]
  },
  {
    "id": "3ab448d0-9d2c-4752-9832-28f238b36651",
    "name": "Jiří Folajtár",
    "givenName": "Jiří",
    "familyName": "Folajtár",
    "sortName": "Folajtár Jiří",
    "memberOf": [
      {
        "id": "89395259-1fd2-4a28-8a86-537ecf69944f"
      }
    ]
  },
  {
    "id": "f92343a6-ff84-4050-8ec5-dd4fac9c2dfe",
    "name": "Jiří Drahoš",
    "givenName": "Jiří",
    "familyName": "Drahoš",
    "sortName": "Drahoš Jiří",
    "memberOf": [
      {
        "id": "970162b0-ec51-4f39-81e7-1d99f7bd7cc3"
      }
    ]
  },
  {
    "id": "a0b9f0db-cdbe-462b-a7fc-3c308a5b8331",
    "name": "Filip Outrata",
    "givenName": "Filip",
    "familyName": "Outrata",
    "sortName": "Outrata Filip",
    "memberOf": [
      {
        "id": "758b3394-1927-477c-81bb-4bb4605fd3ef"
      }
    ]
  },
  {
    "id": "495a9acd-f79c-4a9b-8e26-69f440076a0a",
    "name": "Markéta Šichtařová",
    "givenName": "Markéta",
    "familyName": "Šichtařová",
    "sortName": "Šichtařová Markéta",
    "memberOf": [
      {
        "id": "6797d805-5e00-4f26-acb5-a61f8b4895ba"
      }
    ]
  },
  {
    "id": "ff426663-f8e6-4fd5-808d-92c0ce6dddf8",
    "name": "Petr Štěpánek",
    "givenName": "Petr",
    "familyName": "Štěpánek",
    "sortName": "Štěpánek Petr",
    "memberOf": [
      {
        "id": "0150f4df-0865-4577-8ccb-04f5b399e2a2"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/23-praha-8/persons.json
[
  {
    "id": "b450202c-2395-449b-9bf2-7a5a98fa3e7c",
    "name": "Zdeněk Kučera",
    "givenName": "Zdeněk",
    "familyName": "Kučera",
    "sortName": "Kučera Zdeněk",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "dfe1afe6-ede8-4dbb-836e-a2a8af101e1a",
    "name": "Vladimíra Ludková",
    "givenName": "Vladimíra",
    "familyName": "Ludková",
    "sortName": "Ludková Vladimíra",
    "memberOf": [
      {
        "id": "eeef1d79-7c04-42e4-a427-5ceb9ae9df1a"
      }
    ]
  },
  {
    "id": "5173229c-a118-4f48-971b-c385d14747d9",
    "name": "Pavel Fischer",
    "givenName": "Pavel",
    "familyName": "Fischer",
    "sortName": "Fischer Pavel",
    "memberOf": [
      {
        "id": "966d63f4-4986-4345-9c8e-7a9fbc66c37b"
      }
    ]
  },
  {
    "id": "f066f840-0ea3-4725-9d6e-207510e2cfd6",
    "name": "Lukáš Wagenknecht",
    "givenName": "Lukáš",
    "familyName": "Wagenknecht",
    "sortName": "Wagenknecht Lukáš",
    "memberOf": [
      {
        "id": "fac96e1b-54cc-4cc0-840e-9443f154c03f"
      }
    ]
  },
  {
    "id": "9d35bea2-4525-4917-a3a7-d785bbd7e606",
    "name": "David Kopecký",
    "givenName": "David",
    "familyName": "Kopecký",
    "sortName": "Kopecký David",
    "memberOf": [
      {
        "id": "758b3394-1927-477c-81bb-4bb4605fd3ef"
      }
    ]
  },
  {
    "id": "1b9a7949-1edc-4f2d-aaaf-9d2e0e38572c",
    "name": "Vítězslav Novák",
    "givenName": "Vítězslav",
    "familyName": "Novák",
    "sortName": "Novák Vítězslav",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "5e767100-8654-4ef3-a8ba-e30cd01a3677",
    "name": "Miroslav Erbrt",
    "givenName": "Miroslav",
    "familyName": "Erbrt",
    "sortName": "Erbrt Miroslav",
    "memberOf": [
      {
        "id": "6797d805-5e00-4f26-acb5-a61f8b4895ba"
      }
    ]
  },
  {
    "id": "7e6681ca-7e9c-48ac-ad32-ef8958c17f68",
    "name": "Jan Korda",
    "givenName": "Jan",
    "familyName": "Korda",
    "sortName": "Korda Jan",
    "memberOf": [
      {
        "id": "01d12899-6c90-4cc3-bb57-a21d5a927529"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/26-praha-2/persons.json
[
  {
    "id": "3f7556bd-601a-40f9-8314-5f47079ea8af",
    "name": "Eva Kislingerová",
    "givenName": "Eva",
    "familyName": "Kislingerová",
    "sortName": "Kislingerová Eva",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "47f1dfbe-1b60-4bcb-942d-b19ed56133cf",
    "name": "Eva Zažímalová",
    "givenName": "Eva",
    "familyName": "Zažímalová",
    "sortName": "Zažímalová Eva",
    "memberOf": [
      {
        "id": "f87f4d6b-f2d5-49fa-8a38-2757be7d3309"
      }
    ]
  },
  {
    "id": "234fa6b7-3f3a-423a-8ae9-db666041b7e5",
    "name": "Marek Hilšer",
    "givenName": "Marek",
    "familyName": "Hilšer",
    "sortName": "Hilšer Marek",
    "memberOf": [
      {
        "id": "f0a84417-fb42-4554-b3c5-316e9733110d"
      }
    ]
  },
  {
    "id": "f3f2fd9d-a281-44b0-b6c3-845ccb809809",
    "name": "Bronislav Poul",
    "givenName": "Bronislav",
    "familyName": "Poul",
    "sortName": "Poul Bronislav",
    "memberOf": [
      {
        "id": "758b3394-1927-477c-81bb-4bb4605fd3ef"
      }
    ]
  },
  {
    "id": "21c85646-fd70-4ebc-aea9-894f9c6e5719",
    "name": "Miroslav Bárta",
    "givenName": "Miroslav",
    "familyName": "Bárta",
    "sortName": "Bárta Miroslav",
    "memberOf": [
      {
        "id": "a4af352c-2d35-4c43-8b81-8a3a2ab8180e"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/65-sumperk/persons.json
[
  {
    "id": "e6f4f22a-9957-4c72-be64-44330a134e1c",
    "name": "Miroslav Adámek",
    "givenName": "Miroslav",
    "familyName": "Adámek",
    "sortName": "Adámek Miroslav",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "42e96abd-a256-41c6-89b6-1a638453244a",
    "name": "Stanislav Balík",
    "givenName": "Stanislav",
    "familyName": "Balík",
    "sortName": "Balík Stanislav",
    "memberOf": [
      {
        "id": "8331b263-fda5-459d-b28c-ddb84f281963"
      }
    ]
  },
  {
    "id": "aeae66ba-8dcd-4fda-a581-565f65ae22d3",
    "name": "Vladimír Hošek",
    "givenName": "Vladimír",
    "familyName": "Hošek",
    "sortName": "Hošek Vladimír",
    "memberOf": [
      {
        "id": "6797d805-5e00-4f26-acb5-a61f8b4895ba"
      }
    ]
  }
]

=== kalkulacka-one/kalkulacka/apps/web/public/data/instance/volebnikalkulacka.cz/senatni-2024/56-breclav/persons.json
[
  {
    "id": "f439ae8f-eb3a-440d-96f0-f9de020899e2",
    "name": "Miloslav Janulík",
    "givenName": "Miloslav",
    "familyName": "Janulík",
    "sortName": "Janulík Miloslav",
    "memberOf": [
      {
        "id": "e8833483-680f-435a-af44-b759327578c8"
      }
    ]
  },
  {
    "id": "11a17925-3e54-452a-b252-0be1661099a3",
    "name": "Rostislav Koštial",
    "givenName": "Rostislav",
    "familyName": "Koštial",
    "sortName": "Koštial Rostislav",
    "memberOf": [
      {
        "id": "64a0008f-2d59-4a0f-961f-8fa2fd1a7835"
      }
    ]
  },
  {
    "id": "c45ac450-a3a2-4370-9d83-e9360cc104b0",
    "name": "Stanislav Šprtel",
    "givenName": "Stanislav",
    "familyName": "Šprtel",
    "sortName": "Šprtel Stanislav",
    "memberOf": [
      {
        "id": "40a4e263-ec72-417a-8e6f-f97297351b13"
      }
    ]
  },
  {
    "id": "c9fcea15-00be-479c-9cec-9729bb65690e",
    "name": "Rudolf Kadlec",
    "givenName": "Rudolf",
    "familyName": "Kadlec",
    "sortName": "Kadlec Rudolf",
    "memberOf": [
      {
        "id": "a58c608d-34db-40bf-9c0b-7e1de5e39200"
      }
    ]
  },
  {
    "id": "b02b5044-0c56-47a6-ac05-2a66b305a435",
    "name": "Zbyněk Hromek",
    "givenName": "Zbyněk",
    "familyName": "Hromek",
    "sortName": "Hromek Zbyněk",
    "memberOf": [
      {
        "id": "952ed13b-c9ab-44cd-9019-3a19431aa4d9"
      }
    ]
  },
  {
    "id": "5d77997d-0145-48d7-a51b-15165ef5cc30",
    "name": "Róbert Šlachta",
    "givenName": "Róbert",
    "familyName": "Šlachta",
    "sortName": "Šlachta Róbert",
    "memberOf": [
      {
        "id": "14aa404d-35be-421d-aa87-fe6b3e2e7ae6"
      }
    ]
  },
  {
    "id": "809cc70d-b813-4edb-9d7c-13b509b3a755",
    "name": "David Malinkovič",
    "givenName": "David",
    "familyName": "Malinkovič",
    "sortName": "Malinkovič David",
    "memberOf": [
      {
        "id": "758b3394-1927-477c-81bb-4bb4605fd3ef"
      }
    ]
  },
  {
    "id": "b58736c2-f6fb-478c-8e96-277380a93e9b",
    "name": "Zdeněk Koudelka",
    "givenName": "Zdeněk",
    "familyName": "Koudelka",
    "sortName": "Koudelka Zdeněk",
    "memberOf": [
      {
        "id": "5cb5d56c-688e-4b55-a801-8a803d939aab"
      }
    ]
  },
  {
    "id": "9764d4dd-1cad-4475-81ef-acc196bb6dca",
    "name": "Josef Osička",
    "givenName": "Josef",
    "familyName": "Osička",
    "sortName": "Osička Josef",
    "memberOf": [
      {
        "id": "15630910-e388-4038-bfeb-04781a6cf2d6"
      }
    ]
  }
]
